### ISSUE TITLE
MqttDataTransport client-id illegal character

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1533] opened 2017-07-17 11:23 UTC
It seems that there is another illegal character (beside  `/`, `+`, `#` and `.`) in the MqttDataTransport client-id configuration that should be replaced with `-`: `$`.

I tested with `c/l*i-e-n+t` vs. `c/l*i-e-n+t$` producing the following logs:

```
2017-07-17 10:47:14,164 [qtp8829195-165] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1500288220946...
2017-07-17 10:47:14,324 [qtp8829195-165] INFO  o.e.k.c.c.ConfigurationServiceImpl - Merging configuration for pid: org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport
2017-07-17 10:47:14,367 [qtp8829195-165] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport ... Done.
2017-07-17 10:47:14,372 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.t.m.MqttDataTransport - Updating org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport...
2017-07-17 10:47:14,374 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Notified DataTransportService configuration updating...
2017-07-17 10:47:14,374 [Component Resolve Thread (Bundle 7)] WARN  o.e.k.c.d.t.m.MqttDataTransport - MQTT client already disconnected
2017-07-17 10:47:14,374 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.t.m.MqttDataTransport - Building new configuration...
2017-07-17 10:47:14,375 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Notified DataTransportService configuration updated.
2017-07-17 10:47:14,375 [pool-11-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED slow blinking
2017-07-17 10:47:14,375 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Starting reconnect task with initial delay 8
2017-07-17 10:47:14,410 [qtp8829195-165] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1500288434368.xml...
2017-07-17 10:47:14,460 [qtp8829195-165] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1500288434368.xml... Done.
2017-07-17 10:47:14,462 [qtp8829195-165] INFO  o.e.k.c.c.ConfigurationServiceImpl - Snapshots Garbage Collector. Deleting /opt/eclipse/kura/data/snapshots/snapshot_1500284575054.xml
2017-07-17 10:47:22,376 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Connecting...
2017-07-17 10:47:22,377 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2017-07-17 10:47:22,378 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connection Properties
2017-07-17 10:47:22,379 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  broker    = tcp://broker-sandbox.everyware-cloud.com:1883
2017-07-17 10:47:22,379 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  clientId  = c-l*i-e-n-t
2017-07-17 10:47:22,380 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  username  = me_broker
2017-07-17 10:47:22,380 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  password  = XXXXXXXXXXXXXX
2017-07-17 10:47:22,381 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  keepAlive = 30
2017-07-17 10:47:22,381 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  timeout   = 20
2017-07-17 10:47:22,382 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  cleanSession    = true
2017-07-17 10:47:22,383 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  MQTT version    = 3.1.1
2017-07-17 10:47:22,383 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willDestination = $EDC/.../c-l*i-e-n-t/MQTT/LWT
2017-07-17 10:47:22,384 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  willMessage     = 
2017-07-17 10:47:22,384 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #
2017-07-17 10:47:22,385 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connecting...
2017-07-17 10:47:22,386 [pool-11-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED fast blinking
2017-07-17 10:47:23,031 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - #  Connected!
2017-07-17 10:47:23,031 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - # ------------------------------------------------------------
2017-07-17 10:47:23,032 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Notified connected
2017-07-17 10:47:23,033 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - New session established. Unpublishing all in-flight messages. Disregarding the QoS level, this may cause duplicate messages.
2017-07-17 10:47:23,036 [pool-11-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED on
2017-07-17 10:47:23,201 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :$EDC/#account-name/#client-id/MQTT/BIRTH, priority: 0
2017-07-17 10:47:23,207 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic :$EDC/#account-name/#client-id/MQTT/BIRTH, priority: 0
2017-07-17 10:47:23,214 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: $EDC/.../c-l*i-e-n-t/MQTT/BIRTH with QoS: 0
2017-07-17 10:47:23,220 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Subscribing to topic: $EDC/.../c-l*i-e-n-t/# with QoS: 1
2017-07-17 10:47:23,493 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.Cloudlet - Cloud Client Connection Restored
2017-07-17 10:47:23,495 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.Cloudlet - Cloud Client Connection Restored
2017-07-17 10:47:23,495 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.Cloudlet - Cloud Client Connection Restored
2017-07-17 10:47:23,496 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.Cloudlet - Cloud Client Connection Restored
2017-07-17 10:47:23,496 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.t.m.MqttDataTransport - Subscribing to topic: .../c-l*i-e-n-t/myapp/xmltopic with QoS: 0
2017-07-17 10:47:23,619 [DataServiceImpl:ReconnectTask] INFO  o.e.k.c.d.DataServiceImpl - Connected. Reconnect task will be terminated.
```
vs.
```
2017-07-17 10:47:38,261 [qtp8829195-154] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1500288434368...
2017-07-17 10:47:38,314 [qtp8829195-154] INFO  o.e.k.c.c.ConfigurationServiceImpl - Merging configuration for pid: org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport
2017-07-17 10:47:38,350 [qtp8829195-154] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport ... Done.
2017-07-17 10:47:38,356 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.t.m.MqttDataTransport - Updating org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport...
2017-07-17 10:47:38,361 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Notified DataTransportService configuration updating...
2017-07-17 10:47:38,362 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.t.m.MqttDataTransport - Disconnecting...
2017-07-17 10:47:38,363 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Notified disconnecting
2017-07-17 10:47:38,365 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Storing message on topic :$EDC/#account-name/#client-id/MQTT/DC, priority: 0
2017-07-17 10:47:38,370 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Stored message on topic :$EDC/#account-name/#client-id/MQTT/DC, priority: 0
2017-07-17 10:47:38,372 [DataServiceImpl:Submit] INFO  o.e.k.c.d.t.m.MqttDataTransport - Publishing message on topic: $EDC/.../c-l*i-e-n-t/MQTT/DC with QoS: 0
2017-07-17 10:47:38,397 [qtp8829195-154] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1500288458351.xml...
2017-07-17 10:47:38,453 [qtp8829195-154] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1500288458351.xml... Done.
2017-07-17 10:47:38,454 [qtp8829195-154] INFO  o.e.k.c.c.ConfigurationServiceImpl - Snapshots Garbage Collector. Deleting /opt/eclipse/kura/data/snapshots/snapshot_1500284859059.xml
2017-07-17 10:47:39,385 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.t.m.MqttDataTransport - Disconnected
2017-07-17 10:47:39,386 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.DataServiceImpl - Notified disconnected
2017-07-17 10:47:39,387 [pool-11-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED off
2017-07-17 10:47:39,387 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.d.t.m.MqttDataTransport - Building new configuration...

... and then nothing happens
```

In the former case the client connects successfully, in the latter it doesn't seem to even try connecting.

Kura 3.1.0-SNAPSHOT on RPi3

**Comment by MMaiero** [comment] 2019-12-16 14:11
Closing as the issue is solved in 4.2.0-SNAPSHOT probably due to the updated Paso dependency.

**Closed as completed by MMaiero** 2019-12-16 14:11 UTC
Labels: bug, kura-cloud
