### ISSUE TITLE
[Kura 2.1.0 QA] Problems with installation of Kura on BeagleBone Black

### ISSUE THREAD

**Issue by djurod** [eclipse/kura#930] opened 2016-12-12 14:17 UTC
Issues with the [documentation](https://eclipse.github.io/kura/doc/beaglebone-quick-start.html):
- Required dependencies are not listed: isc-dhcp-server, dos2unix, bind9, bind9utils, unzip, ethtool and telnet
- The "connman" service needs to be disabled, otherwise the network configuration functionality of Kura doesn't work.
- The systemd's time-sync service needs to be disabled, otherwise it interferes with the time sync. functionality of Kura.

Installation issues:
- Install log (kura_install_<ts>.log) errors:
    ```
    cp: cannot create regular file '/var/named/': Not a directory
    ```
- Console log (kura-console.log) errors:
    A lot of exceptions were thrown and it looks like the reason is this (workaround can be found in #548):
    ```
    Caused by: java.lang.UnsatisfiedLinkError: /tmp/.kura/configuration/org.eclipse.osgi/bundles/62/1/.cp/lib/linux/armv6_hf/libEurotechLinuxUdev.so: libudev.so.0: cannot open shared object file: No such file or directory
    ```
- Because of the issue from above web interface doesn't load.

Kura 2.1.0 build 15 on BeagleBone Black

**Comment by ctron** [comment] 2016-12-12 16:24
Looks like a duplicate of #321 and #548

**Comment by ctron** [comment] 2016-12-12 16:24
There should be a way to reconfigure the "libudev" rules to also trigger the libudev.so.1 variant which is currently used for Fedberry.

**Comment by cdealti** [comment] 2016-12-15 11:13
> Required dependencies are not listed: isc-dhcp-server, dos2unix, bind9, bind9utils, unzip, ethtool and telnet

Does ``gdebi`` (see #850) help?

If so please take note of the need to update the documentation on your validation spreadsheet.

> The "connman" service needs to be disabled, otherwise the network configuration functionality of Kura doesn't work.

Please take notes

> The systemd's time-sync service needs to be disabled, otherwise it interferes with the time sync. functionality of Kura.

Please take notes

> Install log (kura_install_.log) errors:
> cp: cannot create regular file '/var/named/': Not a directory

Please go ahead with the validation and check if NET-ETH0-011 passes

> Console log (kura-console.log) errors:
> A lot of exceptions were thrown and it looks like the reason is this (workaround can be found in #548):
> Caused by: java.lang.UnsatisfiedLinkError: /tmp/.kura/configuration/org.eclipse.osgi/bundles/62/1/.cp/lib/linux/armv6_hf/libEurotechLinuxUdev.so: libudev.so.0: cannot open shared object file: No such file or directory

Yes this is a duplicate #321 #548.
Please take note of the need to create the softlink for the time being.
There is a proper fix and I'll take a look.

Eventually your notes on the validation spreadsheet will be used to update the documentation and create a new revision of the spreadsheet

**Comment by djurod** [comment] 2016-12-15 12:38
> Does gdebi (see #850) help?
Yes.

**Comment by djurod** [comment] 2016-12-15 13:57
I added a note to the verification spreadsheet regarding:
- connman
- time sync issue
- libudev issue

Regarding the /var/named/ log entry, the test NET-ETH0-011 passed in build 15.

In build 16 there are no more issues if you follow the new instructions and ignore the /var/named/ log entry.

@cdealti: As far as I am concerned this issue can be closed now.

**Comment by cdealti** [comment] 2016-12-19 14:41
@djurod before closing this, let's see if we can easily fix the libudev link above.

Can you please try the following?

1. Copy the org.eclipse.kura.linux.usb jar in /opt/eclipse/kura/kura/plugins on a Linux PC
2. Double click on the jar. The Linux archive manager should open it
3. Modify the META-INF MANIFEST.MF adding the following line to the ``Bundle-NativeCode`` header:
 ``
lib/linux/armv7hl_fedora/libEurotechLinuxUdev.so; osname=Linux; processor=ARM; selection-filter="(&(kura.os.version=debian))",
``
add this line just after this one:
 ``lib/linux/armv7hl_fedora/libEurotechLinuxUdev.so; osname=Linux; processor=ARM; selection-filter="(&(kura.os.version=fedora))",``
4. Save the MANIFEST.MF. The archive manager will ask you to update the jar contents
5. Copy the jar to the beaglebone replacing the original one
6. Remove the softlink to libudev and restart Kura

References:
https://github.com/eclipse/kura/blob/release-2.1.0/kura/distrib/pom.xml
https://github.com/eclipse/kura/blob/release-2.1.0/kura/org.eclipse.kura.linux.usb/META-INF/MANIFEST.MF

**Comment by cdealti** [comment] 2016-12-20 13:23
@nicolatimeus can you please test the last comment?

**Comment by cdealti** [comment] 2016-12-21 14:27
Close via #967

**Closed by cdealti** 2016-12-21 14:27 UTC
Labels: bug, documentation, P2, QA
