### ISSUE TITLE
Multiple bluetooth le devices connection problem

### ISSUE THREAD

**Issue by dwoodard1** [eclipse/kura#80] opened 2016-01-06 21:58 UTC
This bug was original reported at https://bugs.eclipse.org/bugs/show_bug.cgi?id=480434.

Original messages:

In the release version 1.2.2 or version 1.3.0 RC1, one bluetooth le device (e.g. TI SensorTag) works well, but if you try to connect 2 or more bluetooth le devices, the second one couldn't connect. However, due to bluetooth specs, it should be OK to connect several bluetooth le devices at the same time.

GitHub Pull Request 66 created by [gavinying]
https://github.com/eclipse/kura/pull/66

**Comment by pierantoniomerlino** [comment] 2016-01-07 11:22
The issue is related to Bluetooth LE example, not to the bluetooth service.
The bug is already fixed in the develop branch and it will be included in the next Kura release.

**Closed** 2016-01-07 11:22 UTC
