### ISSUE TITLE
Undescriptive Generic Error When Port Number Longer Than 4 Digits

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2777] opened 2020-04-07 11:04 UTC
If user enters 5 digit number into the "Port on Port Range" field, Kura returns an undescriptive generic error (see screenshot bellow). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click "new" and add "72000" as port number
3. Click Submit
4. After that click "Apply" and observe the error

**Expected behavior**
If error/warning is thrown, there should be a description of what is wrong and/or how to fix it. 

**Screenshot:**
![Screenshot 2020-04-07 at 08 45 20](https://user-images.githubusercontent.com/15121999/78638343-67d5e300-78ac-11ea-9492-9d6974bfd55f.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.1.0

**Comment by pierantoniomerlino** [comment] 2020-04-09 13:08
@LeoNerdoG  I'm not able to reproduce this issue. AFAIK, Kura doesn't implement a rule on port digit length.

**Comment by LeoNerdoG** [comment] 2020-04-09 13:15
Hej @pierantoniomerlino,
I have to update the testflow - after you press the Apply button, the error appears, not when you click Submit. Can you please follow the updated testflow above and report if you are able to reproduce? 
I have rollback-ed the device to seeded snapshot, deleted cache and history in my brwoser and I was able to reproduce the issue. Can you please check again?

**Comment by pierantoniomerlino** [comment] 2020-04-09 13:21
@LeoNerdoG Ah ok, thanks. I can reproduce the issue now. It is the same as #2779.
The port value has to be in (0:65535]. So I'll add an additional check.

**Comment by pierantoniomerlino** [comment] 2020-04-22 15:20
Closed by #2796

**Closed as completed by pierantoniomerlino** 2020-04-22 15:20 UTC

**Comment by LeoNerdoG** [comment] 2020-05-06 06:17
I have verified that this issue has been successfully resolved.
