### ISSUE TITLE
Some Problem about Kura Wires

### ISSUE THREAD

**Issue by OrangeAlex** [eclipse/kura#1633] opened 2017-09-01 08:56 UTC
Hi, 
    After i install the Kura on the Raspberry and then  i  install the OPC UA simulator and OPC UA Driver on it . So  i fellow the tutorial Titled "OPC/UA application in Kura Wires",and configure the simulator port :1234 
and then i configure the OPC UA Diver IP:localhost,Port:1234 , and then i use the Wires , Add four components like tutorial show, and then i connect them. According last sentence of the tutorial , i can check the data from the log and publisher. but  i do not know how to check .
I think i must config the Logger component and publisher component , but how to config them , where could i get the data that when the simulator start?
     Any good suggestion?

**Comment by MMaiero** [comment] 2017-09-01 12:08
Hi,
the log is the kura.log file available in the /var/log folder.
The publisher component publishes mqtt messages to a configured remote broker. So, to have a look at the published messages, you should have a look at your remote mqtt broker.

Best regards,
Matteo

**Comment by OrangeAlex** [comment] 2017-09-04 02:31
@MMaiero  hi , MMaiero, I hava chech the log under the path /var/log/kura.log,  i found some error info as fellows :[DefaultQuartzScheduler_Worker-3]ERROR o.e.k.i.w.a.WireAsset - OpcUaMessages.errorRetrievingNodeId
this info appears 6 times at the same time in the log , so i think it has some error during the message delivering, so  how to deal with it ?
Meanwhile , i want to know how to use the kura access the real OPC UA Device , i  can  not find any tutorial from official website, do you have any suggestion?

**Comment by MMaiero** [comment] 2017-09-04 06:37
Did you properly configure the driver to connect to the opc-ua server?
Did you double check the matching of the channels with the ones specified in the documentation? Please consider that also the case is important.

Regarding the connection to a real device, in theory, what you'll need to change is the endpoint in the driver and the channels in the asset. But here everything depends on the target device and is not easily manageable in a tutorial.

Best regards

**Comment by OrangeAlex** [comment] 2017-09-04 07:38
@MMaiero my configuration as fellows:
OPCUA Server Demo:
server.port
The server listening port:1234
OPC UA Driver:
endpoint.ip
OPC-UA Endpoint IP Address:localhost
endpoint.port
OPC-UA Endpoint Port:1234
server.name
OPC-UA Server Name:empty
session.timeout
Session Timeout(in seconds):120
request.timeout
Request timeout(in seconds):60
application.name
OPC-UA application name:opc-ua client
application.uri
OPC-UA application uri:urn:kura:opcua:client
certificate.location
OPC-UA application certificate(Absolute Location):PFX or JKS Keystore
security-policy
Security-Policy:None
username
OPC-UA server username:none
password
OPC-UA server password
Keystore.client.alias
Server alias for the keystore:server-ai
keystore.type
Keystore type:PKCS12
keystore.password
Configurable Properly to set keystore password(default set to password):

i check them again ,  all the configuration i  made is same to the official tutorial , so  i  can not know where is the mistake ? Maybe i miss something about the configuration?
Do you have any good suggestion?

By the way , i  watch the video from the youtube about kura using, i found before usting the Kura wires , the actor connect Kura to the cloud platform first, so i wonder to know , Is the Connecting the Cloud necessary step? 

Best regards,
Alex.wang

**Comment by MMaiero** [comment] 2017-09-04 08:39
> Is the Connecting the Cloud necessary step?

No.

**Comment by MMaiero** [comment] 2017-09-04 08:41
> Do you have any good suggestion?

Not at the moment. I believe the best option is to post the log from kura.log and kura-console.log, in order to see if there is something strange there. 
Which is the asset configuration?

**Comment by OrangeAlex** [comment] 2017-09-04 08:59
@MMaiero  hi MMaiero, in the Kura Wires, I create asset component with six Channels base on OPCUA Driver , the configuration as fellows :
name    type              value type      OpcUaMessages.nodeId         OpcUaMessages.nodeNamespaceIndex
fan       READ_WRITE  INTEGER            fan                                             2
buzzer        READ       INTEGER            buzzer                                        2
light           READ        INTEGER            lightSensor                                2
temperature   READ   DOUBLE             temperatureSensor                   2
led           READ_WRITE   INTEGER        led                                             2
water       READ              BOOLEAN       waterSensor                              2

asset.desc
AssetMessage.description:Sample Asset

**Comment by OrangeAlex** [comment] 2017-09-06 02:49
@MMaiero  would you have some good suggestion about my problem?

**Comment by MMaiero** [comment] 2017-09-06 07:58
Hi,
I'm still waiting for your kura.log and kura-console.log files in order to perform some checks and analysis there.

I suspect that your issue can be caused by the locale you are using in the raspberry.

Best regards,
Matteo

**Comment by OrangeAlex** [comment] 2017-09-06 10:02
[kura-console.log.txt](https://github.com/eclipse/kura/files/1280639/kura-console.log.txt)


[kura.log.zip](https://github.com/eclipse/kura/files/1280655/kura.log.zip)

@MMaiero  hi MMaiero, the attachment is the log of my Kura, so  i have no experience to find the error , please give me some suggestion, thank you very much

**Comment by MMaiero** [comment] 2017-09-06 14:54
Could you please try to switch your locale setup to English/us?
We have found an issue with drivers that we are currently solving. 
Maybe that could help.

**Comment by OrangeAlex** [comment] 2017-09-07 03:55
@MMaiero hi MMaiero, i reset the locale setup to English/us, and then i delete the all the component in the Wires, and then  i create  three new component "Timer","Asset"base on OPCUA Driver ,"Logger",and the Asset has four channel, the node id is "fan","temperatureSensor","led","waterSensor", i connected them together , and click the button "Apply" on the web , i chech the logger , I think the problem i asked you before has been deal with ,
the log show me the information as fellows :
2017-08-31 01:32:51,023 [pool-9-thread-1] INFO  o.e.k.c.s.r.LogStatusRunnable - Notification LED slow blinking
2017-08-31 01:32:51,876 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask started.
2017-08-31 01:32:51,876 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask: Check store...
2017-08-31 01:32:51,888 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask: Delete confirmed messages...
2017-08-31 01:32:51,900 [HouseKeeperTask] INFO  o.e.k.c.d.s.HouseKeeperTask - HouseKeeperTask ended.
2017-08-31 01:32:53,190 [DefaultQuartzScheduler_Worker-10] INFO  o.e.k.i.w.l.Logger - Received WireEnvelope from org.eclipse.kura.wire.WireAsset-1504113353645-31
2017-08-31 01:32:55,214 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (434)
2017-08-31 01:32:55,217 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2017-08-31 01:33:00,214 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (435)
2017-08-31 01:33:00,215 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2017-08-31 01:33:03,193 [DefaultQuartzScheduler_Worker-1] INFO  o.e.k.i.w.l.Logger - Received WireEnvelope from org.eclipse.kura.wire.WireAsset-1504113353645-31
2017-08-31 01:33:03,468 [DnsMonitorServiceImpl] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
2017-08-31 01:33:04,406 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Deleting configuration for pid OPCUA
2017-08-31 01:33:04,411 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Removing Wires...
2017-08-31 01:33:04,421 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Removing Wires...Done
2017-08-31 01:33:04,422 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Removing Wires...
2017-08-31 01:33:04,428 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Removing component configuration for pid OPCUA
2017-08-31 01:33:04,429 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Creating new configuration for factory pid org.eclipse.kura.wire.WireAsset and pid OPCUA
2017-08-31 01:33:04,429 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating newly created configuration for pid OPCUA
2017-08-31 01:33:04,454 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Removing Wires...Done
2017-08-31 01:33:04,463 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering ConfigurableComponent - OPCUA....
2017-08-31 01:33:04,464 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering ConfigurableComponent - OPCUA....Done
2017-08-31 01:33:04,479 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been removed by Asset Cloudlet Tracker....BaseAsset [Asset Configuration=AssetConfiguration [channels={fan=Channel [configuration={node.id=fan, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=fan, type=READ_WRITE, valueType=INTEGER], temperature=Channel [configuration={+value.type=DOUBLE, node.id=temperatureSensor, +type=READ, node.namespace.index=2, +name=STRING}, name=temperature, type=READ, valueType=DOUBLE], led=Channel [configuration={node.id=led, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=led, type=READ_WRITE, valueType=INTEGER]}, description=Sample Asset, driverPid=OPCUADriver]]
2017-08-31 01:33:04,486 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Removing component configuration for pid org.eclipse.kura.wire.WireAsset-1504113353645-31
2017-08-31 01:33:04,487 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.d.o.OpcUaDriver - Disconnecting from OPC-UA...
2017-08-31 01:33:04,508 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.d.o.OpcUaDriver - Disconnecting from OPC-UA...Done
2017-08-31 01:33:04,509 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been removed by the driver tracker...org.eclipse.kura.internal.driver.opcua.OpcUaDriver@43f69b
2017-08-31 01:33:04,594 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been found by the driver tracker....==> adding service
2017-08-31 01:33:04,601 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire between OPCUA and Logger....
2017-08-31 01:33:04,622 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire.....Done
2017-08-31 01:33:04,623 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire between Timer and OPCUA....
2017-08-31 01:33:04,641 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire.....Done
2017-08-31 01:33:04,671 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been found by Asset Cloudlet Tracker....==> adding service
2017-08-31 01:33:04,993 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1504113354631...
2017-08-31 01:33:05,214 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (436)
2017-08-31 01:33:05,215 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2017-08-31 01:33:05,252 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Merging configuration for pid: org.eclipse.kura.wire.WireAsset
2017-08-31 01:33:05,270 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent OPCUA ... Done.
2017-08-31 01:33:05,271 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering SelfConfiguringComponent - OPCUA....
2017-08-31 01:33:05,271 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering SelfConfiguringComponent - OPCUA....Done
2017-08-31 01:33:05,303 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been removed by the driver tracker...org.eclipse.kura.internal.driver.opcua.OpcUaDriver@43f69b
2017-08-31 01:33:05,305 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been found by the driver tracker....==> adding service
2017-08-31 01:33:05,315 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been removed by Asset Cloudlet Tracker....BaseAsset [Asset Configuration=AssetConfiguration [channels={fan=Channel [configuration={node.id=fan, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=fan, type=READ_WRITE, valueType=INTEGER], temperature=Channel [configuration={+value.type=DOUBLE, node.id=temperatureSensor, +type=READ, node.namespace.index=2, +name=STRING}, name=temperature, type=READ, valueType=DOUBLE], led=Channel [configuration={node.id=led, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=led, type=READ_WRITE, valueType=INTEGER], water=Channel [configuration={+value.type=BOOLEAN, node.id=waterSensor, node.namespace.index=2, +type=READ, +name=STRING}, name=water, type=READ, valueType=BOOLEAN]}, description=Sample Asset, driverPid=OPCUADriver]]
2017-08-31 01:33:05,317 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been found by Asset Cloudlet Tracker....==> adding service
2017-08-31 01:33:05,330 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been removed by the driver tracker...org.eclipse.kura.internal.driver.opcua.OpcUaDriver@43f69b
2017-08-31 01:33:05,332 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been found by the driver tracker....==> adding service
2017-08-31 01:33:05,345 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been removed by Asset Cloudlet Tracker....BaseAsset [Asset Configuration=AssetConfiguration [channels={fan=Channel [configuration={node.id=fan, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=fan, type=READ_WRITE, valueType=INTEGER], temperature=Channel [configuration={+value.type=DOUBLE, node.id=temperatureSensor, +type=READ, node.namespace.index=2, +name=STRING}, name=temperature, type=READ, valueType=DOUBLE], led=Channel [configuration={node.id=led, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=led, type=READ_WRITE, valueType=INTEGER], water=Channel [configuration={+value.type=BOOLEAN, node.id=waterSensor, node.namespace.index=2, +type=READ, +name=STRING}, name=water, type=READ, valueType=BOOLEAN]}, description=Sample Asset, driverPid=OPCUADriver]]
2017-08-31 01:33:05,347 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been found by Asset Cloudlet Tracker....==> adding service
2017-08-31 01:33:05,365 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been removed by the driver tracker...org.eclipse.kura.internal.driver.opcua.OpcUaDriver@43f69b
2017-08-31 01:33:05,367 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been found by the driver tracker....==> adding service
2017-08-31 01:33:05,379 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been removed by Asset Cloudlet Tracker....BaseAsset [Asset Configuration=AssetConfiguration [channels={fan=Channel [configuration={node.id=fan, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=fan, type=READ_WRITE, valueType=INTEGER], temperature=Channel [configuration={+value.type=DOUBLE, node.id=temperatureSensor, +type=READ, node.namespace.index=2, +name=STRING}, name=temperature, type=READ, valueType=DOUBLE], led=Channel [configuration={node.id=led, +value.type=INTEGER, +type=READ_WRITE, node.namespace.index=2, +name=STRING}, name=led, type=READ_WRITE, valueType=INTEGER], water=Channel [configuration={+value.type=BOOLEAN, node.id=waterSensor, node.namespace.index=2, +type=READ, +name=STRING}, name=water, type=READ, valueType=BOOLEAN]}, description=Sample Asset, driverPid=OPCUADriver]]
2017-08-31 01:33:05,380 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.c.AssetTrackerCustomizer - Asset has been found by Asset Cloudlet Tracker....==> adding service
2017-08-31 01:33:05,513 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Loading init configurations from: 1504113354631...
2017-08-31 01:33:05,622 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Updating Configuration of ConfigurableComponent org.eclipse.kura.wire.WireService ... Done.
2017-08-31 01:33:05,630 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire between OPCUA and Logger....
2017-08-31 01:33:05,632 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire.....Done
2017-08-31 01:33:05,634 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire between Timer and OPCUA....
2017-08-31 01:33:05,635 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.w.WireServiceImpl - Creating wire.....Done
2017-08-31 01:33:05,807 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1504114385623.xml...
2017-08-31 01:33:05,827 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Writing snapshot - Saving /opt/eclipse/kura/data/snapshots/snapshot_1504114385623.xml... Done.
2017-08-31 01:33:05,830 [qtp20859490-39] INFO  o.e.k.c.c.ConfigurationServiceImpl - Snapshots Garbage Collector. Deleting /opt/eclipse/kura/data/snapshots/snapshot_1504110604127.xml

so  i have three question:
1. according to the log , i found the asset and driver will be removed
2017-08-31 01:33:04,486 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Removing component configuration for pid org.eclipse.kura.wire.WireAsset-1504113353645-31
2017-08-31 01:33:04,487 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.d.o.OpcUaDriver - Disconnecting from OPC-UA...
2017-08-31 01:33:04,508 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.d.o.OpcUaDriver - Disconnecting from OPC-UA...Done
2017-08-31 01:33:04,509 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been removed by the driver tracker...org.eclipse.kura.internal.driver.opcua.OpcUaDriver@43f69b
2017-08-31 01:33:04,594 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.i.a.p.DriverTrackerCustomizer - Driver has been found by the driver tracker....==> adding service
whyl is it ? Does it mean that there still have some problem, and the data has not been delivered successfully ?

2. this question is about the configuration of component "Timer", the Timer has to a Type to be set, but i do not know how to set , i use the default option "SIMPLE", but according to the tutorial , the interval should configure at which the OPC/UA Server will be sampled , so how to set Timer component correctly

3.i do not know where is the data received , so how to check
[kura.zip](https://github.com/eclipse/kura/files/1283410/kura.zip)

**Comment by MMaiero** [comment] 2017-09-07 12:28
> according to the log , i found the asset and driver will be removed

This is the normal behaviour. If you don't see exceptions in the log, I believe you are ok.

> this question is about the configuration of component "Timer", the Timer has to a Type to be set, but i do not know how to set , i use the default option "SIMPLE", but according to the tutorial , the interval should configure at which the OPC/UA Server will be sampled , so how to set Timer component correctly

That depends on your needs. If you set a higher frequency in the timer, then more frequently the OPC-UA device will be polled and the data retrieved. 

> i do not know where is the data received , so how to check

If you have set a logger after the asset you can see that the messages are logged. Setting the log level to "Verbose" you can have a look at what was retrieved by the OPC-UA asset. From what I see in the log, you have placed a publisher block but you have not configured a cloud service to connect to, so the messages are not sent by Kura.

**Comment by OrangeAlex** [comment] 2017-09-11 09:57
@MMaiero  hi， MMaiero, i have change the log level to the "Verbose",and then  i found information in the log as fellows :
2017-08-31 09:54:09,386 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger - Received WireEnvelope from org.eclipse.kura.wire.WireAsset-1504142299752-3
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger - Record List content: 
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -   Record content: 
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     water_timestamp : 1504144449385
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     fan : 0
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     temperature : 27.73619031429145
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     assetName : OPCUA
2017-08-31 09:54:09,387 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     fan_timestamp : 1504144449360
2017-08-31 09:54:09,388 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     led : 0
2017-08-31 09:54:09,388 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     water : false
2017-08-31 09:54:09,388 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     temperature_timestamp : 1504144449368
2017-08-31 09:54:09,388 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger -     led_timestamp : 1504144449376
2017-08-31 09:54:09,388 [DefaultQuartzScheduler_Worker-7] INFO  o.e.k.i.w.l.Logger - 
2017-08-31 09:54:10,825 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (430)
2017-08-31 09:54:10,832 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2017-08-31 09:54:15,825 [AbstractNtpClockSyncProvider:schedule] INFO  o.e.k.l.c.AbstractNtpClockSyncProvider - Try to sync clock (431)
2017-08-31 09:54:15,826 [AbstractNtpClockSyncProvider:schedule] WARN  o.e.k.l.c.JavaNtpClockSyncProvider - Error while synchronizing System Clock with NTP host 0.pool.ntp.org. Please verify network connectivity ...
2017-08-31 09:54:19,394 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger - Received WireEnvelope from org.eclipse.kura.wire.WireAsset-1504142299752-3
2017-08-31 09:54:19,395 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger - Record List content: 
2017-08-31 09:54:19,395 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -   Record content: 
2017-08-31 09:54:19,395 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     water_timestamp : 1504144459394
2017-08-31 09:54:19,396 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     fan : 0
2017-08-31 09:54:19,396 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     temperature : 22.752485568935608
2017-08-31 09:54:19,396 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     assetName : OPCUA
2017-08-31 09:54:19,396 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     fan_timestamp : 1504144459364
2017-08-31 09:54:19,397 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     led : 0
2017-08-31 09:54:19,397 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     water : true
2017-08-31 09:54:19,397 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     temperature_timestamp : 1504144459373
2017-08-31 09:54:19,397 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger -     led_timestamp : 1504144459382
2017-08-31 09:54:19,398 [DefaultQuartzScheduler_Worker-8] INFO  o.e.k.i.w.l.Logger - 

Does it mean that i have received the data from OPCUA Asset successfully?
what is your opinion?
Best regards

**Comment by MMaiero** [comment] 2017-09-11 09:59
Yes. I believe we can close the issue now.

**Comment by OrangeAlex** [comment] 2017-09-11 10:05
@MMaiero  by the way , i have another question about the kura , if i have a device based on the opc ua , i want to access it  via the kura,  so  i think , i should configure an ip and the port number in the kura , and then the device send the request to the kura through the ip and port, and i think i can browse the data from the log as same as i did before via Kura Wires ? is that right ?
what is your opinion or suggestion?
Best regards

**Comment by MMaiero** [comment] 2017-09-11 10:14
You can do that in the same way as done in the example: the Kura Wires component and Driver act as an OPC-UA client and connect to a remote OPC-UA server. If that is the context, you can simply change the IP and port in the driver instance to point to your remote asset. Furthermore, you'll need to update the asset with a proper set of channels.

If you need Kura to be an OPC-UA server, currently we have no components to do that but you'll have to wrap another project, for example Eclipse MIlo, to do that.

**Comment by OrangeAlex** [comment] 2017-09-11 10:20
@MMaiero  OK  MMaiero, Thank you very much for your help,^_^
Best regards, Alex.wang

**Closed as completed** 2017-09-11 10:22 UTC
