### ISSUE TITLE
The list of Cloud Services has disappeared by stoping and restarting kura 

### ISSUE THREAD

**Issue by marentwickler** [eclipse/kura#1573] opened 2017-07-31 12:47 UTC
Hello,
if I have stoped and restarted  kura , the list of Cloud Services is disappeared, and I get Error, if I click button Cloud Services on left menu :
The Error:
Mon Jul 31 13:40:49 GMT+100 2017 ErrorLogger INFO: GwtCloudService_Proxy: INTERNAL_ERRORorg.eclipse.kura.web.shared.GwtKuraException: INTERNAL_ERROR
   at Unknown.tg(denali-0.js)
   at Unknown.Bg(denali-0.js)
   at Unknown.Sfc(denali-0.js)
   at Unknown.Xfc(denali-0.js)
   at Unknown.hdb(denali-0.js)
   at Unknown.ddb(denali-0.js)
   at Unknown.Bbb(denali-0.js)
   at Unknown.jcb(denali-0.js)
   at Unknown.sr(denali-0.js)
   at Unknown.Gr(denali-0.js)
   at Unknown.eval(denali-0.js)
   at Unknown.Ch(denali-0.js)
   at Unknown.Fh(denali-0.js)
   at Unknown.eval(denali-0.js)

I use Kura 3.00, Rasperry Pi.
How can I save my actual cloud configuration?

![screen shot 2017-07-31 at 13 46 09](https://user-images.githubusercontent.com/11528983/28778326-b91d76c6-75f6-11e7-9047-f6a52c64552c.png)

from Log file:
2017-07-31 12:51:23,346 [qtp2427252-62] WARN  o.e.k.w.s.s.SkinServlet - Resource Directory /opt/eclipse/kura/console/skin does not exist
2017-07-31 12:51:23,347 [qtp2427252-66] WARN  o.e.k.w.s.s.SkinServlet - Resource Directory /opt/eclipse/kura/console/skin does not exist
2017-07-31 12:51:23,548 [qtp2427252-66] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2017-07-31 12:51:23,700 [qtp2427252-35] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2017-07-31 12:51:24,903 [qtp2427252-66] WARN  o.e.k.n.a.v.l.WpaSupplicantConfigReader - WPA in client mode is not configured
2017-07-31 12:51:30,579 [DnsMonitorServiceImpl] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty

thanks in advance

**Comment by dwoodard1** [comment] 2017-07-31 23:09
@marentwickler The information from the log file is just warnings and not relevant to the error. Do you see any errors in the log file? Do you see any errors in /var/log/kura-console.log? Can you please login to the OSGi console (telnet localhost 5002) and issue the 'ls' command?

**Comment by marentwickler** [comment] 2017-08-01 13:03
hello @dwoodard1,
I see any error in /var/log/kura-console.log, and  in Device informations under Bundels the bundel  

55 | org.eclipse.kura.core.cloud   |  Active   |   1.1.0

and on Status  the Cloud services is not empty, it exist all Cloud services with their information.

thanks in advance

**Comment by cdealti** [comment] 2017-08-02 11:50
@marentwickler can you please type `ls` in the OSGi console, find the id of the `org.eclipse.kura.cloud.CloudService` component, type `comp <id>` and post the output here?

**Comment by MMaiero** [comment] 2017-08-25 14:06
@marentwickler Any update?

**Comment by MMaiero** [comment] 2017-08-29 10:18
Closing, since there is no update. You can reopen it at any time ​if needed.

**Closed as completed by MMaiero** 2017-08-29 10:18 UTC

**Comment by Bertola87** [comment] 2018-01-24 21:38
Hello , I receive the same error message when trying to selct the CloudService
osgi services status is : 

osgi> ls
All Components:
ID      State                   Component Name                  Located in bundle
1       Active          org.eclipse.equinox.event                       org.eclipse.equinox.event(bid=7)
2       Active          org.eclipse.kura.data.DataService                       org.eclipse.kura.core(bid=51)
3       Active          org.eclipse.kura.db.DbService                   org.eclipse.kura.core(bid=51)
4       Active          org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport                     org.eclipse.kura.core(bid=51)
5       Active          org.eclipse.kura.ssl.SslManagerService                  org.eclipse.kura.core(bid=51)
6       Active          org.eclipse.kura.system.SystemService                   org.eclipse.kura.core(bid=51)
7       Active          org.eclipse.kura.system.SystemAdminService                      org.eclipse.kura.core(bid=51)
8       Active          org.eclipse.kura.cloud.CloudService                     org.eclipse.kura.core.cloud(bid=52)
9       Registered              org.eclipse.kura.cloud.CloudCallService                 org.eclipse.kura.core.cloud(bid=52)
10      Active          org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactory                  org.eclipse.kura.core.cloud(bid=52)
11      Active          org.eclipse.kura.cloud.app.command.CommandCloudApp                      org.eclipse.kura.core.cloud(bid=52)
12      Active          org.eclipse.kura.core.comm.CommConnectionFactory                        org.eclipse.kura.core.comm(bid=53)
13      Active          org.eclipse.kura.core.configuration.CloudConfigurationHandler                   org.eclipse.kura.core.configuration(bid=54)
14      Active          org.eclipse.kura.configuration.ConfigurationService                     org.eclipse.kura.core.configuration(bid=54)
15      Active          org.eclipse.kura.certificate.CertificatesService                        com.eurotech.framework.security.certificatesmanager(bid=55)
16      Active          org.eclipse.kura.crypto.CryptoService                   com.eurotech.framework.security.manager(bid=56)
17      Active          org.eclipse.kura.core.deployment.CloudDeploymentHandlerV2                       org.eclipse.kura.core.deployment(bid=57)
18      Active          org.eclipse.kura.log.LoggerService                      org.eclipse.kura.core.log(bid=58)
19      Active          org.eclipse.kura.status.CloudConnectionStatusService                    org.eclipse.kura.core.status(bid=60)
20      Active          org.eclipse.kura.deployment.agent                       org.eclipse.kura.deployment.agent(bid=61)
21      Active          org.eclipse.kura.clock.ClockService                     org.eclipse.kura.linux.clock(bid=62)
22      Registered              org.eclipse.kura.command.CommandService                 org.eclipse.kura.linux.command(bid=63)
23      Active          org.eclipse.kura.position.PositionService                       org.eclipse.kura.linux.position(bid=64)
24      Active          org.eclipse.kura.usb.UsbService                 org.eclipse.kura.linux.usb(bid=66)
25      Active          org.eclipse.kura.bluetooth.BluetoothService                     org.eclipse.kura.linux.bluetooth(bid=67)
26      Active          org.eclipse.kura.watchdog.WatchdogService                       org.eclipse.kura.linux.watchdog(bid=68)
27      Registered              org.eclipse.kura.protocol.modbus.ModbusProtocolDevice                   org.eclipse.kura.protocol.modbus(bid=69)
28      Active          com.eurotech.framework.terminal.service.TerminalClientService                   com.eurotech.framework.terminal.client.server(bid=70)
29      Active          com.eurotech.framework.terminal.service.TerminalServerService                   com.eurotech.framework.terminal.client.server(bid=70)
30      Active          com.eurotech.framework.net.vpn.client.VpnClient                 com.eurotech.framework.net.vpn.client(bid=75)
31      Registered              org.eclipse.kura.bluetooth.BluetoothConnector                   org.eclipse.kura.linux.bluetooth.impl(bid=78)
32      Active          org.eclipse.kura.provisioning.ProvisioningService                       org.eclipse.kura.core.provisioning(bid=79)
33      Active          org.eclipse.kura.protocol.can.CanConnectionServiceImpl                  org.eclipse.kura.protocol.can(bid=80)
34      Active          org.eclipse.kura.web.Console                    org.eclipse.kura.web2(bid=82)
35      Active          com.eurotech.framework.protocol.serial.rs485.rg2025.rs485                       com.eurotech.framework.protocol.serial.rs485.rg2025(bid=83)
36      Unsatisfied             org.eclipse.kura.asset                  org.eclipse.kura.asset.provider(bid=84)
37      Active          org.eclipse.kura.asset.cloudlet                 org.eclipse.kura.asset.cloudlet.provider(bid=85)
38      Active          org.eclipse.kura.asset.AssetService                     org.eclipse.kura.asset.helper.provider(bid=86)
39      Active          org.eclipse.kura.driver.DriverService                   org.eclipse.kura.driver.helper.provider(bid=87)
40      Unsatisfied             org.eclipse.kura.wire.CloudPublisher                    org.eclipse.kura.wire.component.provider(bid=91)
41      Unsatisfied             org.eclipse.kura.wire.CloudSubscriber                   org.eclipse.kura.wire.component.provider(bid=91)
42      Unsatisfied             org.eclipse.kura.wire.DbWireRecordFilter                        org.eclipse.kura.wire.component.provider(bid=91)
43      Unsatisfied             org.eclipse.kura.wire.DbWireRecordStore                 org.eclipse.kura.wire.component.provider(bid=91)
44      Unsatisfied             org.eclipse.kura.wire.Fifo                      org.eclipse.kura.wire.component.provider(bid=91)
45      Unsatisfied             org.eclipse.kura.wire.Logger                    org.eclipse.kura.wire.component.provider(bid=91)
46      Unsatisfied             org.eclipse.kura.wire.RegexFilter                       org.eclipse.kura.wire.component.provider(bid=91)
47      Unsatisfied             org.eclipse.kura.wire.Timer                     org.eclipse.kura.wire.component.provider(bid=91)
48      Unsatisfied             org.eclipse.kura.wire.WireAsset                 org.eclipse.kura.wire.component.provider(bid=91)
49      Active          org.eclipse.kura.wire.WireHelperService                 org.eclipse.kura.wire.helper.provider(bid=92)
50      Registered              org.eclipse.kura.wire.WireServiceCommand                        org.eclipse.kura.wire.provider(bid=93)
51      Active          org.eclipse.kura.wire.WireService                       org.eclipse.kura.wire.provider(bid=93)
52      Active          org.eclipse.kura.gpio.GPIOService                       org.eclipse.kura.linux.gpio(bid=94)
53      Active          org.eclipse.kura.net.NetworkService                     org.eclipse.kura.linux.net(bid=95)
54      Active          org.eclipse.kura.net.dns.DnsMonitorService                      org.eclipse.kura.net.admin(bid=96)
55      Active          org.eclipse.kura.net.EthernetMonitorService                     org.eclipse.kura.net.admin(bid=96)
56      Active          org.eclipse.kura.net.admin.FirewallConfigurationService                 org.eclipse.kura.net.admin(bid=96)
57      Active          org.eclipse.kura.net.CellularMonitorService                     org.eclipse.kura.net.admin(bid=96)
58      Active          org.eclipse.kura.net.admin.NetworkAdminService                  org.eclipse.kura.net.admin(bid=96)
59      Active          org.eclipse.kura.net.admin.NetworkConfigurationService                  org.eclipse.kura.net.admin(bid=96)
60      Active          org.eclipse.kura.net.WifiMonitorService                 org.eclipse.kura.net.admin(bid=96)

**Comment by MMaiero** [comment] 2018-01-25 07:19
Hello,
could you please provide a set of steps in order to reproduce the issue?
Which version of Kura are you using?

Best regards,
Matteo

**Comment by Bertola87** [comment] 2018-01-25 08:20
Hello Matteo 
the last thing I did , I installed Modbus drivers and OPC-UA driver and server , following the tutorial in Kura website. OPC UA Driver

I'm running Kura 5.0.0 on an Eurotech Reliagate 
thank you kind regards

**Comment by MMaiero** [comment] 2018-01-25 13:39
Removing the installed bundles does not solve the issue?

**Comment by Bertola87** [comment] 2018-01-30 22:52
Hello MMAiero , 
back on this topic ( apologize for the delay but I had to solve some other buisiness in the meantime) 
how can I de-insintall bundles from command line without using the web interface of kura? 
I'm still facing the same issue described , here's the kura-console.log file : 

!ENTRY org.eclipse.kura.core.cloud 2 0 2018-01-30 22:50:43.812!MESSAGE [SCR] ComponentReference.unbind(): component instance not bound! It is: org.eclipse.equinox.internal.ds.impl.ComponentInstanceImpl@684a8ce1        Details:        Problematic reference = Reference[name = DataService, interface = org.eclipse.kura.data.DataService, policy = static, cardinality = 1..1, target = null, bind = setDataService, unbind = unsetDataService]        of service component = org.eclipse.kura.cloud.CloudService        component implementation class = org.eclipse.kura.core.cloud.CloudServiceImpl        located in bundle with symbolic name = org.eclipse.kura.core.cloud        bundle location = initial@reference:file:../kura/plugins/org.eclipse.kura.core.cloud_1.1.0.jar
thank you kind regards

      Da: MMaiero <notifications@github.com>
 A: eclipse/kura <kura@noreply.github.com> 
Cc: Bertola87 <andrea.bertola@yahoo.it>; Comment <comment@noreply.github.com>
 Inviato: Giovedì 25 Gennaio 2018 8:19
 Oggetto: Re: [eclipse/kura] The list of Cloud Services has disappeared by stoping and restarting kura (#1573)
   
Hello,
could you please provide a set of steps in order to reproduce the issue?
Which version of Kura are you using?Best regards,
Matteo—

**Comment by MMaiero** [comment] 2018-01-31 08:46
Hi,
it seems to be a trouble on the data service service. It should be good to know which were the exact actions that took to this result.
I might be wrong, but I doubt that installing the OPCUA driver can break the cloud service stack. It seems more a wrong configuration of the data service / Mqtt data service bundles.

In any case, as you are using a commercial product, I would suggest you to refer to the official support from the producer.

Best regards,
Matteo
