### ISSUE TITLE
Create Maven plugin capable of wrapping regular bundles in DP packages

### ISSUE THREAD

**Issue by hekonsek** [eclipse/kura#231] opened 2016-05-20 10:41 UTC
Majority of Camel users are used to using plain OSGi bundles. We should provide plugin wrapping such bundles into DP packages.

**Comment by ctron** [comment] 2016-07-22 07:56
I found one [1] ... although I didn't try it.

[1] http://mvn-dp-plugin.sourceforge.net/site/index.html

**Comment by cdealti** [comment] 2016-08-11 09:55
@ctron I think I tried it three years ago but it did not work for what we had in mind at that time (Kura itself was a big dp)

**Comment by cdealti** [comment] 2016-08-11 11:49
@ctron Can you confirm the decision we make for Camel?
1. org.apache.camel:camel-core
2. org.apache.camel:camel-osgi
3. org.apache.camel:camel-kura
4. org.apache.camel:camel-stream
5. org.eclipse.kura.camel

These will be included in the Kura runtime by default.

Other Camel components will be added as extended downloads (Deployment Packages, Features etc).

**Comment by ctron** [comment] 2016-08-16 07:28
I am not sure this comment was intended for this issue. But yes, that would be the plan. Beside that we want to try setting up Kura with Karaf and when the need for some important bundle arises we can add it to the default distribution.

In general I think it would be great to split up Kura itself for distributing parts of it as DPs. Or using P2.

Maybe it would be a good idea to rethink the way the Kura build process currently creates DPs so that this can be streamlined a bit.

**Comment by ctron** [comment] 2016-08-18 08:02
@cdealti Ok, I created a Maven plugin which will simply create a DP from an Eclipse Feature built with Tycho during the build process.

```xml
<dependency>
    <groupId>de.dentrassi.maven</groupId>
    <artifactId>osgi-dp</artifactId>
    <version>0.0.1</version>
</dependency>
```

We just do need to add this in the next build-and-test-CQ!

**Comment by ctron** [comment] 2016-09-01 09:16
This is available in the PR #469

**Comment by ctron** [comment] 2016-09-01 13:05
https://ctron.github.io/osgi-dp/

**Comment by MMaiero** [comment] 2016-10-20 18:13
@ctron Can we close this? Maybe this plugin has to be documented somewhere in our documentation. What you think?

**Comment by ctron** [comment] 2016-10-20 19:26
I guess we can close it. There is some documentation with the plugin already.

https://ctron.github.io/osgi-dp/

**Closed** 2016-10-21 07:32 UTC
Labels: kura-camel
