### ISSUE TITLE
Kura Accessible on Two Different IPs?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2905] opened 2020-05-27 07:25 UTC
I think this is really not a Kura issue, but maybe you guys can help me out. 
I have Kura 4.2.0_SNAPSHOT (latest) installed on my Raspeberry and the IP shown in Kura is 10.19.40.103 (screenshot bellow). But my Kura device is also accessible through IP 10.19.40.102? How is this possible, is there a residual configuration somewhere on my machine or...?
I have 2 devices on my network, but other is on x.x.x.147, so this one does not interfere.

**Testflow:**
? - I don't really know how to reproduce this yet - if I figure it out, I will post it here

**Expected behavior**
If kura has only one interface active (e.g. eth0), it should be accessible through one IP only. 

**Screenshot:**
![Screenshot 2020-05-27 at 07 49 58](https://user-images.githubusercontent.com/15121999/82984246-0bf92200-9ff2-11ea-8540-289e53d6ea4d.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment] 2020-06-12 15:03
Does this persist?
Does a reboot of the device or (more likely) of the router solves this?

I don't think this is indeed a problem in Kura if the ifconfig actually returns the expected IP

**Comment by MMaiero** [comment] 2020-08-26 10:27
@MMaiero Can you check if you are able to reproduce? Otherwise, I believe we can close the issue for now

**Comment by LeoNerdoG** [comment] 2020-08-26 10:52
Hey @MMaiero, I have checked this and the problem persists. 
I have changed offices in the mean time, so the IP addresses are now 10.17.81.50 and 10.17.81.59 (but this is the same device, I checked MAC addresses).

**Comment by MMaiero** [comment] 2020-08-26 12:45
@pierantoniomerlino any clue on this? I believe I have never seen it.

**Comment by pierantoniomerlino** [comment] 2020-08-26 12:48
@LeoNerdoG on the terminal type `ip addr` and check if two addresses are associated to eth0. I saw that on my RPi... I think that is permitted by the OS [1]

[1] https://www.raspberrypi.org/forums/viewtopic.php?t=237765

**Comment by LeoNerdoG** [comment] 2020-08-28 07:08
Hey @pierantoniomerlino, Yes, I get two IPs:
![Screenshot 2020-08-28 at 09 08 26](https://user-images.githubusercontent.com/15121999/91534775-6c11a400-e912-11ea-890b-2693429f5b13.png)


So - do we keep this issue open?

**Comment by pierantoniomerlino** [comment] 2020-08-28 07:32
@LeoNerdoG I don't see the two IPs: eth0 has only 10.17.81.59... It should be something like this:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:b8:c9:d6 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.170/24 brd 192.168.0.255 scope global dynamic eth0
       valid_lft 7133sec preferred_lft 7133sec
    inet 192.168.0.200/24 brd 192.168.0.255 scope global secondary eth0:1
       valid_lft forever preferred_lft forever
```

However, IMHO we can close this issue since it's harmless.

Edit: now I see that! Thanks!

**Comment by LeoNerdoG** [comment] 2020-08-28 07:46
Hey @pierantoniomerlino I have uploaded wrong screenshot - I have changed it, so now you can see the two different IPs. 
Ok, I agree with you that this can be closed, I would just like to conduct several tests and then close it, just to be sure.

**Closed as completed** 2020-08-31 11:07 UTC
