### ISSUE TITLE
Error appears after changing console username/password

### ISSUE THREAD

**Issue by mstankovic** [eclipse/kura#2565] opened 2019-10-30 12:36 UTC
**Describe the bug**
Error message appears after changing console username and password 
error message is `404 ProxyServlet: /admin/denali/xsrf` 

**To Reproduce**
1. Go to WebConsole
2. Change values for username and password
3. Click on Apply button
4. Click "Yes" to confirm changing

**Expected behavior**
Username and password should be changed without error appearing 

**Screenshots**
![console_password](https://user-images.githubusercontent.com/3385815/67858564-c63ab080-fb19-11e9-8d62-6dbd5e24e76d.PNG)

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3 (also able to reproduce on RG10-20)
 - Kura version: 4.2-SNAPSHOT 

**Additional context**
- username and password are changed 
- there is no error in kura.log
- unable to reproduce on Kura 4.1

**Comment by spnettec** [comment] 2019-10-30 13:29
I can't reproduce this. Can you try docker run -d -p 1883:1883  -p 8080:80 -p 443:443 -p 8088:8088  --name kura heyoulin/kura:v4.2.11   ?

**Comment by nicolatimeus** [comment] 2019-10-30 16:13
It it probably caused by the fact that some Console servlets are unregistered and re-registered when the WebConsole configuration is updated.
Maybe we can improve the code to avoid unnecessary restarts depending on the parameters that actually changed.

**Comment by spnettec** [comment] 2019-10-30 18:38
> It it probably caused by the fact that some Console servlets are unregistered and re-registered when the WebConsole configuration is updated.
> Maybe we can improve the code to avoid unnecessary restarts depending on the parameters that actually changed.

@nicolatimeus You are right. I compared my revision. I found i had resoved this bug long time ago.
You can see my fork. I can comiit a PR

**Comment by mstankovic** [comment] 2019-10-31 15:05
Im confirming that PR #2567 fixes this issue.
Thanks @spnettec @nicolatimeus

**Comment by mstankovic** [comment] 2021-03-07 16:26
@MMaiero we should close this issue and related PR?

**Comment by MMaiero** [comment] 2021-03-07 16:29
Issue fixed with latest changes in UI

**Closed as completed by MMaiero** 2021-03-07 16:29 UTC
