### ISSUE TITLE
Where is The DNS Server List?

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2888] opened 2020-05-20 08:01 UTC
If user sets wlan0's status to "Enabled for WAN", the "DNS Servers" option gets enabled. If user hoovers above the field, it says: 
"List of DNS servers. New servers can be added by entering an address and clicking apply.
To remove a server, delete the address from the list and click apply". 
Is this list meant to be in the UI or on the device itself, and thereofre deletable only if user ssh's itself onto the device?

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> wlan0 -> TCP/IP
3. Set Status to "Enabled for WAN"
4. Hoover above the DNS Servers and observe the description of the field on the right

**Expected behavior**
Should there be a list of DNS servers in the UI?

**Screenshot:**
![Screenshot 2020-05-20 at 09 48 51](https://user-images.githubusercontent.com/15121999/82421054-c92ecb80-9a80-11ea-8e1d-9c4204934acb.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment] 2020-05-20 16:00
@LeoNerdoG The issue is not clear to me.

In theory, the user can specify its own DNS server there like 1.1.1.1 and have dns names resolved from that instead of the one set by the network.

**Comment by LeoNerdoG** [comment] 2020-05-21 06:30
Hey @Matteo,
the problem here is not in the field itself or with the DNS server entry , but in the description of the field. There is a part in decription that says: "To remove a server, delete the address from the list and click apply" - what does this actually mean? Shold there be a list of DNS servers in the UI? Because there isn't any and I was just wondering if this is an issue?

**Comment by MMaiero** [comment] 2020-05-21 07:04
Ok, got it. I agree can be misleading. I believe that we can maybe remove that sentence. What do you think?

**Comment by LeoNerdoG** [comment] 2020-05-21 07:29
Yes, I agree. If there is no list in the UI that would made this possible (removing DNS entries),t hen this part should be removed.

**Comment by MMaiero** [comment] 2020-06-19 12:11
I was reviewing this issue. 
We actually have the possibility to add multiple dns server addresses using ; or spaces between IPs.
The view is actually not great.
I have tried to sketch a possible change in #2956. Maybe if you can have a look. Probably a change in the description is still needed but maybe the management is simple using a text area

**Comment by MMaiero** [comment] 2020-07-01 14:25
@LeoNerdoG Since #2956 has been merged, can this be closed in your opinion?

**Comment by LeoNerdoG** [comment] 2020-07-02 10:56
Hey @MMaiero,
I have checked this and the original issue is resolved. 
However, I have discovered that user can enter only spaces or semicolons and Kura will not report an error (screenshot bellow) - I think we should open a new issue for this - what do you think? 
Or can you fix this with a new PR and link it with this issue? 

![Screenshot 2020-07-02 at 12 54 50](https://user-images.githubusercontent.com/15121999/86350771-793c4a80-bc63-11ea-8f8e-675514af7929.png)

**Closed as completed** 2020-07-08 13:26 UTC
Labels: bug, cleanup

**Comment by LeoNerdoG** [comment] 2020-07-10 06:10
I have verified that this issue has been resolved.
