### ISSUE TITLE
"Router Mode" Settings Ignored

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2901] opened 2020-05-25 11:06 UTC
If user changes the "Router Mode" to DHCP & NAT, changes some settings (e.g. DHCP beginning and ending address), saves changes, reloads the page and returns to this tab, the "Router Mode" is in "NAT only".  

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network -> eth0 -> Configure
3. Set the Configure to "Manually"
4. Go to DHCP & NAT tab
5. Change the Router mode to DCHP & NAT
6. Change DHCP beginning and ending address, apply changes
7. Reload browser window and return to the tab - observe the setting.

**Expected behavior**
If user selects of sets certain paramters, they should stay that way or Kura should report an error when trying to save the configuration.

**Screenshot:**
![Screenshot 2020-05-25 at 11 18 21](https://user-images.githubusercontent.com/15121999/82798876-75095a00-9e79-11ea-8e6b-37c30450ceb1.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Kura version: 4.2.0_SNAPSHOT ([Link to the specific Kura version -from May 20th 2020](https://ci.eclipse.org/kura/job/kura-develop/lastSuccessfulBuild/artifact/kura/distrib/target/kura_4.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb)

**Comment by MMaiero** [comment] 2020-06-12 15:33
Hi @LeoNerdoG, It's not clear to me, from the steps if you are saving the configuration and when.

**Comment by LeoNerdoG** [comment] 2020-06-16 06:53
Hey @MMaiero,
you are right, I forgot to add the applying part - it is in step 6, after you change the DHCP starting and ending address.

**Comment by MMaiero** [comment] 2020-07-08 15:26
What are you setting in the TCP/IP section precisely?

**Comment by LeoNerdoG** [comment] 2020-07-10 08:45
I leave all the parameters as they are from before (when DHCP assignes them):
 - Status: enabled for LAN
 - Configure: Manually
 - IP Address :10.19.40.105
 - subnet mask: 255.255.255.0

**Comment by sterwen** [comment] 2020-07-20 10:16
I have exactly the same behavior while generating a snapshot file with a router mode on WiFi (Version 4.0), it always appear as NAT Only. For all the parameters are OK in the snapshot, but I never succeeded to have the correct settings applied. Maybe not the same bug, but results looks similar.

**Comment by MMaiero** [comment] 2020-07-20 11:44
@sterwen Do you have any meaningful error in the logs?

**Comment by sterwen** [comment] 2020-07-21 14:57
Did not find anything in the logs that trace an error while configure the wlan0. After further analysis, I am not convinced that the problem we observe has the same root cause.

**Comment by MMaiero** [comment] 2020-09-04 15:56
I cannot replicate this issue in my test gateway. I will try to verify again this with a raspberry

**Comment by salvatore-coppola** [comment] 2021-06-15 12:51
I cannot replicate the issue either. The dns & nat parameters seem to be properly saved and displayed.
Won't fix.

**Closed as completed** 2021-06-21 13:44 UTC
