### ISSUE TITLE
Kura Configuration: device.custom-name & Device Custom-Name wrongly saved via Kapua Configuration

### ISSUE THREAD

**Issue by larsklichta** [eclipse/kura#4571] opened 2023-04-14 10:40 UTC
**Describe the bug**
I am currently trying to configure my Raspberry PI 4 with Kura 5.3.0 installed, via Kapua.
I can successfully connect to Kapua, but if I go to the configuration tab and for example change the "Device Custom-Name" and save, the "Display Name" won't change.

Kura does get the new configuration and saves it, but the attribute "Display Name" is saved under "device.custom-name" in the Kura Configuration.xml and the Kapua changes are saved under "Device Custom-Name" in the xml.

Other changes like the keep-alive attribute won't change as well.

**To Reproduce**
1. Install Kura 5.3.0 on Raspberry PI 4 (64-bit)
2. Connect to Kapua
3. Select "the device"
4. Select "Configuration"
5. Select "CloudService"
6. Change "Device Custom-Name"
7. Save changes
8. Watch nothing change, aka. see Error.

**Expected behavior**
The "Display Name" or the "Device Custom-Name" under Configuration should change.

**Target Environment**
 - Board: Raspberry PI 4
 - OS version: Raspbian Lite 64-bit
 - Additional info: Kura (5.3.0) & Kapua (1.0.0-M7)

**Comment by MMaiero** [comment] 2023-04-21 06:57
Thanks, we'll have a look at this.

**Comment by MMaiero** [comment] 2023-04-21 07:22
Hi, just checked on my devices and I currently don't see the issue.

This is what I see in Kura 
![Screenshot 2023-04-21 at 09 26 18](https://user-images.githubusercontent.com/10448126/233570892-f65f8996-8469-479c-9500-f0dc471a6846.png)

And Kapua
![Screenshot 2023-04-21 at 09 26 41](https://user-images.githubusercontent.com/10448126/233570926-8e393aa2-9f88-492e-8ef2-83d5bb62f560.png)

Just to check every aspect before going deeper in the code investigation, if you access the Kura device after the change, is the value properly set?
On the Kapua instance, did you try refreshing the configurations with the refresh button?

Thanks

**Comment by larsklichta** [comment] 2023-04-25 07:41
Yes. I already tried to refresh, did not work.

The value on Kura isn't set properly.

In the snapshot file you can find 2 key-values.

Device Custom-Name with the new value from kapua and device_custom-name (or
something similar) with the old value which is displayed in Kura and Kapua.

**Comment by MMaiero** [comment] 2023-04-25 09:36
Can you please upload such snapshot? Thanks

**Comment by MMaiero** [comment] 2023-04-25 16:13
@GregoryIvo @mstankovic Did you see this issue in your QA tests for 5.3.0?

**Comment by GregoryIvo** [comment] 2023-04-25 16:16
@MMaiero I did not encounter this on my end. Perhaps it is due to the version of Kapua I tested against. 
Will try to reproduce this.

**Comment by GregoryIvo** [comment] 2023-04-26 02:18
On the latest release of [kapua 1.6.7](https://github.com/eclipse/kapua/releases/tag/1.6.7), I was unable to reproduce this issue:
![image](https://user-images.githubusercontent.com/29900100/234443829-77704e14-1a2b-4b6f-b51e-c3ed65307e40.png)
![image](https://user-images.githubusercontent.com/29900100/234449214-76570582-2ebe-429c-9f51-5b617d130301.png)


---
On release [1.0.0] I was also unable to reproduce this. (https://github.com/eclipse/kapua/commit/4023414321d7c681de649d9a81b143595e709af8)
![image](https://user-images.githubusercontent.com/29900100/234444910-cb75136e-db5c-4641-aea1-f92e10074c79.png)
![image](https://user-images.githubusercontent.com/29900100/234445353-3f380992-b229-4522-9c9c-33918dc2f481.png)

**Comment by larsklichta** [comment] 2023-04-28 08:05
Hello, sorry for the late response.

My colleague updated Kapua to 1.6.7 and on this version it works.
But the problem on 1.0.0-M7 remains. It's not really important now, but perhaps for others a fix would help.

Here is a picture of the not working snapshot (using Raspberry PI 4, Kura 5.3.0 and Kapua 1.0.0-M7):
![grafik](https://user-images.githubusercontent.com/108763070/235091079-d8a60d33-77f3-4f99-8f59-74eb2318dbec.png)
![grafik](https://user-images.githubusercontent.com/108763070/235091150-e34db1f2-e660-48c6-983c-e852a2f4a657.png)
![grafik](https://user-images.githubusercontent.com/108763070/235091175-485cfac6-4465-453a-b747-fbb0cf60c790.png)

Kapua and Kura use the device.custom-name properties, but the configuration update from Kapua is saved in Device Custom-Name.

**Comment by MMaiero** [comment] 2023-04-28 08:09
Hi, thanks for the info.
I don't think that version is still supported especially since it is a milestone release so not an official one.
Maybe you can circle back the question to the [Eclipse Kapua team](https://github.com/eclipse/kapua).

Since this seems not an issue for Eclipse Kura I'm closing the issue. Feel free to reopen it if needed

**Closed as completed by MMaiero** 2023-04-28 08:09 UTC
