### ISSUE TITLE
No Error Message for Duplicate Certificates

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#3161] opened 2020-11-17 10:07 UTC
If user wants to add e.g. Server SSL Certificate with name ssl-1 and afterwards another one with same content and alias, Kura does not return an error, but it seems that certificate is added anyway (it actually isn't, but behaviour of Kura implies that). 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Security -> Add
3. Selecte HTTPS Server Certificate, add a valid certificate with alias "ssl-1"
4. Try to add another certificate with same content and alias
5. Kura doe snot report an error

**Expected behavior**
Kura should report na error if user wants to add a certificate with non-unique alias. 

**Screenshot:**
/

**Target Environment (please complete the following information):**
 - Board: Raspberry Pi 3
 - OS version: Linux raspberrypi 5.4.72-v7+ 1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - _**Tested branch: PR #3143**_ 

**Additional context**
As stated above, this issue has been found on branch PR 3143 and not on latest develop branch.

**Comment by MMaiero** [comment] 2020-11-24 16:58
Duplicate of #3162 ?

**Closed as completed by MMaiero** 2020-11-24 16:58 UTC
