### ISSUE TITLE
Kura Bluetooth LE support and Bluez 5.x

### ISSUE THREAD

**Issue by IOOOTA** [eclipse/kura#130] opened 2016-04-26 10:00 UTC
I'm trying to use the "org.eclipse.kura.linux.bluetooth" module inside a Linux x86 environment (Debian Jessie).

Debian Jessie comes with bluez 5.23 per default and incidentally I'm obliged to stick to the 5.* version because of specific project's requirements.

Using the methods offered by the org.eclipse.kura.linux.bluetooth.le.BluetoothGattImpl class I have noticed that the it tries to parse the output of the "gatttool" interactive shell, but it uses regular expressions that are **not** compliant with the lines returned by the gatttool shell.

Making a comparison with an installation of bluez4.101 on a different machine I have figured out that Kura's implementation expects **that** output, thus resulting to be compliant with bluez4.101 and not with bluez5.x (at least for what concerns the BLE layer).

I'd like to know if someone else out there have encountered this same kind of problem and if they have worked it around (and how, possibly :-) ).
At the same time, I'm wondering if a migration (or fork) towards Bluez5.x is planned at all or not.

Any hint will be greatly appreciated, thanks in advance.

**Comment by pierantoniomerlino** [comment] 2016-04-26 10:56
Currently Kura supports bluez-4.101 and it expects that the gatttool output is in the "right" format.
In particular, the issue is related on the connect command output. Kura tries to parse the [CON] string, but with Bluez-5.x the connection status is shown with a different font color on gatttool.

So, to support Bluez-5.x, Kura has to manage this different response and check if there are more differences on the gatttool output. The class to be modified is org.eclipse.kura.linux.bluetooth.le.BluetoothGattImpl.java

Currently, we don't have plans to support it. However, any contribution is more than welcome!

**Comment by cdealti** [comment] 2016-05-03 15:44
Possibly duplicate of #179

**Comment by cdealti** [comment] 2016-07-15 16:15
Duplicate of #179

**Closed by cdealti** 2016-07-15 16:15 UTC
Labels: duplicate, kura-bluetooth
