### ISSUE TITLE
[Kura 2.1.0 QA] Wrong range messages

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#917] opened 2016-12-07 15:25 UTC
This applies to all range validation messages.

When entering "-2147483601" as a value for "integer" you get the following message: "Value must be greater than -2147483600".

However "-2147483600" already is a valid message, but it is not greater than "-2147483600".

**Comment by cdealti** [comment] 2016-12-07 17:52
Agreed. Not critical but we can try to fix this.

**Comment by markoer** [comment] 2016-12-12 12:22
Duplicate of #889.

**Closed** 2016-12-16 10:13 UTC
Labels: bug, QA
