### ISSUE TITLE
Replace HSQLDB with H2

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#1421] opened 2017-05-30 17:00 UTC
Using H2 would allow an external application to share the Kura DB enabling new interprocess communication scenarios and integration with external processes (maybe some Python library for edge analytics).

In some scenarios it would be useful to have more that one database, for example an in memory database frequently updated and another one providing some guarantees that rare updates are persisted/flushed to disk.

This scenario can be supported, not surprisingly, by multiple service configurations each with their own settings.

There will be of course a default configuration replacing the current HSQLDB single instance.

**Comment by cdealti** [comment] 2017-06-09 09:48
@nicolatimeus can you please explain the migration path to H2? I understand we plan to support HSQLDB for a while.

**Comment by nicolatimeus** [comment] 2017-06-09 14:49
The switch from HSQL to H2 is a breaking change, this is caused by the fact that the SQL grammar used by the two database engines is slightly different. For this reason existing applications that are using the db directly might no longer work after the update.

This will be addressed performing the migration in two phases:

1.  The next minor Kura releases will introduce H2 and preserve backwards compatibility by having both database engines available to applications. To make this possible the `org.eclipse.kura.db` API package will be refactored in the following way:

    - A new interface, called `BaseDbService`will be introduced, this interface will have the same methods as the current `DbService`interface.
    - `DbService` will be deprecated and becomes an empty interface that extends `BaseDbService`. This service will be provided by the existing HSQL implementation.
    - A new `H2DbService` interface will be introduced, `H2DbService` defines no methods and extends `BaseDbService` as well. This service will be provided by the new H2-based implementation.

    This change makes the APIs expose some implementation-specific details (the fact that H2 is used). This is justified by the fact that a consumer that intends to run some queries on the db must know which Db implementation is using, because this implies using a specific SQL dialect.

    The core Kura components that use the database directly (DataService, WireRecordStore and WireRecordFilter) will be ported to H2 and depend on the new `H2DbService`.
    Existing applications that depend on the legacy `DbService` will continue to consume the HSQL-based implementation, preserving backwards compatibility.

    The HSQL implementation will use a lazy activation policy, in this way it will be activated only if needed and almost no overhead will be introduced if no legacy applications are running.

2. The support for HSQL will be dropped in the next major Kura release, this will be announced in advance to allow existing applications to be ported to H2 in time.

**Closed as completed** 2017-07-03 09:03 UTC
Labels: enhancement
