### ISSUE TITLE
Wrongly Duplicate Entry When Adding Open Ports in Firewall 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2774] opened 2020-04-06 10:52 UTC
If user clicks on "new" button in Firewall, and enters 123 in "port" number, Kura reports a Duplicate error, although there is no open port with the number 123.

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Firewall, click on "new", enter "123" as port number
3. Click "Submit"
4. Without clicking anything else click on "Delete" and confirm the deletion
5. Without anything else click on "New" and enter "123" again - observe the error

**Expected behavior**
There should not be any duplicate error, if the port number is not yet used.

**Screenshot:**
![Screenshot 2020-04-06 at 12 51 42](https://user-images.githubusercontent.com/15121999/78551345-d57b0400-7805-11ea-8e48-e55eefca2acf.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by pierantoniomerlino** [comment] 2020-04-06 14:32
@LeoNerdoG Is it Kura 4.1.0?

**Comment by pierantoniomerlino** [comment] 2020-04-06 14:47
I tried with Kura 4.1.0 and I cannot reproduce the issue. @LeoNerdoG Have you more datail on the procedure? Did you rebooted the device and re-tried?

**Comment by LeoNerdoG** [comment] 2020-04-07 05:28
Hey @pierantoniomerlino,
yes, this is Kura 4.1.0 - I will try again today and update the testflow if you are unable to reproduce this. I was able to reproduce it several times following the testflow.

**Comment by LeoNerdoG** [comment] 2020-04-07 08:14
Hey @pierantoniomerlino,
I have updated the testflow above. The problem is if user does not apply changes between adding new port, deleting it and adding it again - so if you don't apply the changes after you delete the port, it is "stuck" somehow in some state inbetween "delete" and "apply" so...if you can't reproduce it, please let me know.

**Comment by pierantoniomerlino** [comment] 2020-04-07 09:29
@LeoNerdoG After disabling the Edit and Delete buttons when nothing is selected, I can reproduce a similar issue:

1. Login to Kura as admin/admin
2. Go to Firewall, click on "new", enter "123" as port number
3. Click "Submit"
4. Without clicking anything else change tab (discarding the unsaved changes)
5. Go back to the firewall tab and try to add the "123" port
6. Observe the duplication error

**Comment by LeoNerdoG** [comment] 2020-04-07 11:11
Yes, you are right - I just tried this and i could replicate successfully. 
Should this be issue on its own or we leave as part of the existing one?

**Comment by pierantoniomerlino** [comment] 2020-04-07 12:34
IMHO, we could leave it to this issue.

**Comment by pierantoniomerlino** [comment] 2020-04-09 10:35
Ok. The issue is due to the fact that the onCreate method is called multiple times when the "New" button is clicked. I added a walkaround for this in my Kura fork.

**Comment by pierantoniomerlino** [comment] 2020-04-22 15:20
Closed by #2796

**Closed as completed by pierantoniomerlino** 2020-04-22 15:20 UTC

**Comment by LeoNerdoG** [comment] 2020-05-06 06:14
I have verified that this issue has been successfully resolved.
