### ISSUE TITLE
[Kura 2.1.0 QA] Ethernet interface gateway configuration on Raspberry Pi 3

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#867] opened 2016-11-30 13:26 UTC
2 problems were found here:
* NET-ETH0-001: Configure eth0: (in System->Network->eth0 set interface as follows)
     Status: Enabled for LAN
     Configure: Manually
     IP Address: [some_static_address_allowed_on_your_network]
     Subnet Mask: [appropriate_mask_for_your_network]

  * here Gateway cannot be set, but when changes are applied, it is not removed from system routing tables i.e. ```route``` still displays default gateway

* NET-ETH0-003: Configure eth0:
     Status: "Enabled for WAN"
     Gateway: [appropriate_gateway_for_your_network]
     DNS Servers: [appropriate]

  * here Gateway can be set, but a new default gateway is created and the old one is not removed i.e. ```route``` shows 2 default gateways for the same network

Kura 2.1.0 build 12, Raspberry Pi 3, `Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux`

**Comment by cdealti** [comment] 2016-12-01 08:55
@markoer please mention the Test ID.

**Comment by ibinshtok** [comment] 2016-12-01 23:41
I tried NET-ETH0-001 and NET-ETH0-003 today on a Pi2 running this image:Linux eurotech-pi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux, and it worked for me.
Yes, I saw that gateway can't be set if interface is configured for LAN, but I believe this is desirable behaviour since Kura only allows setting default gateway on a WAN interface.
But I did not see any other issues with default gateway. In other words, when eth0 is set from WAN to LAN (static), gateway is removed, and when eth0 is set back to WAN the default gateway is installed. No two default gateways for the same network.
Thinking about those reported symptoms, is there any chance that Network Manager is running?

**Comment by markoer** [comment] 2016-12-02 08:51
Network Manager is not running:
```
# nmcli g
STATE    CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
unknown  unknown       unknown  unknown  unknown  unknown 
```

Starting point: Enabled for WAN, DHCP:
```
# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.XXX.XXX.250    0.0.0.0         UG    202    0        0 eth0
10.XXX.XXX.0      *               255.255.255.0   U     202    0        0 eth0
```

Set Configure to Manually, specify the appropriate GW (the same IP as before):
```
# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.XXX.XXX.250    0.0.0.0         UG    0      0        0 eth0
default         10.XXX.XXX.250    0.0.0.0         UG    202    0        0 eth0
10.XXX.XXX.0      *               255.255.255.0   U     202    0        0 eth0
```

I see you used a different kernel and possibly a different distro. I'm using Raspbian GNU/Linux 8. Maybe that's the reason for the different behavior.

**Comment by ibinshtok** [comment] 2016-12-05 22:51
I was able to recreate this issue on RP 3 imaged as shown below:
1. Installed the 2016-11-25-raspbian-jessie.img
2. Installed, ethtool, hostapd, bind9, telnet, isc-dhcp-server, and vim packages
3. Ran "apt-get update", and "apt-get upgrade"
And I did not even have to install Kura to see it. I looked at the /etc/network/interfaces file and noted that the eth0 interface (as well as wlan0) is set to "manual". If interface is set to manual and network manager of some sort is not running, IP address will not be automatically assigned. But in my case the dhclient was up and IP address was assigned by DHCP server. After I modified settings for eth0 in the /etc/network/interfaces file to look like this (i.e. more similar to the way Kura treats it):
auto eth0
iface eth0 inet dhcp
I got two default gateways. So the solution would to purge the dhcpd5 package as shown below.
4. apt-get purge dhcpcd5
After I did this and installed Kura, it worked fine. @MMaiero please try it and let me know if this works for you. I believe this was introduced when we started using "jessie" insted of “wheezy”.

**Comment by cdealti** [comment] 2016-12-07 09:28
@ibinshtok nice catch.
It looks like the issue is well known and not new:

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=111709

We must include this in the install documentation

**Comment by MMaiero** [comment] 2016-12-07 10:06
@cdealti Yes, yesterday with @ibinshtok we decided to document the issue here and to open another issue in order to track the needed change to the documentation

**Comment by cdealti** [comment] 2016-12-09 11:03
@markoer if it works for you I'd close this

**Comment by markoer** [comment] 2016-12-09 14:36
After removal of dhcpcd5 it works. The issue may be closed.

**Closed** 2016-12-09 16:28 UTC
Labels: bug, P2

**Comment by djurod** [comment] 2016-12-12 14:34
Also an issue on BeagleBone Black (#791).
