### ISSUE TITLE
[Kura 2.1.0 QA] Stack traces are shown in user error messages

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#902] opened 2016-12-07 12:19 UTC
User is presented with error messages such as this one if something unexpected happens in web UI:
```
Wed Dec 07 12:59:55 GMT+100 2016 ErrorLogger INFO: : 12002 com.google.gwt.user.client.rpc.StatusCodeException: 12002 
   at Unknown.gd(Unknown Source)
   at Unknown.ld(Unknown Source)
   at Unknown.td(Unknown Source)
   at Unknown.a0(Unknown Source)
   at Unknown.q0(Unknown Source)
   at Unknown.o2(Unknown Source)
   at Unknown.Zn(Unknown Source)
   at Unknown.no(Unknown Source)
   at Unknown.anonymous(Unknown Source)
   at Unknown.je(Unknown Source)
   at Unknown.me(Unknown Source)
   at Unknown.anonymous(Unknown Source)
```

The expected beahvior would be to present a human-readable error to the user and log the rest.

Kura 2.1.0 build 12

**Comment by ctron** [comment] 2016-12-07 15:47
This is a duplicate of #572

**Comment by cdealti** [comment] 2016-12-09 13:07
Duplicate of #572

**Closed by cdealti** 2016-12-09 13:07 UTC
Labels: duplicate
