### ISSUE TITLE
 client-id parameter for MqttDataTransport must be marked as mandatory in web consol 

### ISSUE THREAD

**Issue by pablochacin** [eclipse/kura#773] opened 2016-11-16 16:40 UTC
The web console doesn't shows the client id as required. If the configuration is updated without providing one value, the following error is generated in the kura log:

>  !MESSAGE [SCR] Exception while modifying instance org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport@5b744373 of component Component[
> 	name = org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport
> 	activate = activate
> 	deactivate = deactivate
> 	modified = updated
> 	configuration-policy = require
> 	factory = null
> 	autoenable = true
> 	immediate = false
> 	implementation = org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport
> 	state = Unsatisfied
> 	properties = 
> 	serviceFactory = false
> 	serviceInterface = [org.eclipse.kura.data.DataTransportService, org.eclipse.kura.ssl.SslServiceListener, org.eclipse.kura.configuration.ConfigurableComponent]
> 	references = {
> 		Reference[name = SystemService, interface = org.eclipse.kura.system.SystemService, policy = static, cardinality = 1..1, target = null, bind = setSystemService, unbind = unsetSystemService]
> 		Reference[name = SslManagerService, interface = org.eclipse.kura.ssl.SslManagerService, policy = static, cardinality = 1..1, target = null, bind = setSslManagerService, unbind = unsetSslManagerService]
> 		Reference[name = CryptoService, interface = org.eclipse.kura.crypto.CryptoService, policy = static, cardinality = 1..1, target = null, bind = setCryptoService, unbind = unsetCryptoService]
> 		Reference[name = CloudConnectionStatusService, interface = org.eclipse.kura.status.CloudConnectionStatusService, policy = static, cardinality = 1..1, target = null, bind = setCloudConnectionStatusService, unbind = unsetCloudConnectionStatusService]
> 		Reference[name = DataTransportListener, interface = org.eclipse.kura.data.DataTransportListener, policy = dynamic, cardinality = 0..n, target = null, bind = null, unbind = null]
> 	}
> 	located in bundle = org.eclipse.kura.core_1.0.9 [47]
> ]
> !STACK 0
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.eclipse.equinox.internal.ds.model.ServiceComponent.modified(ServiceComponent.java:310)
> 	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.modify(ServiceComponentProp.java:187)
> 	at org.eclipse.equinox.internal.ds.InstanceProcess.modifyComponent(InstanceProcess.java:690)
> 	at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationChange(SCRManager.java:523)
> 	at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationEvent(SCRManager.java:385)
> 	at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationEvent(SCRManager.java:303)
> 	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:91)
> 	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
> Caused by: java.lang.IllegalStateException: Invalid MQTT client configuration
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:764)
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.update(MqttDataTransport.java:259)
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.updated(MqttDataTransport.java:244)
> 	... 12 more
> Caused by: org.eclipse.kura.KuraException: The configuration attribute clientId is required and no value has been specified.
> 	at org.eclipse.kura.core.util.ValidationUtil.notEmptyOrNull(ValidationUtil.java:37)
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:685)
> 	... 14 more
> Root exception:
> java.lang.IllegalStateException: Invalid MQTT client configuration
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:764)
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.update(MqttDataTransport.java:259)
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.updated(MqttDataTransport.java:244)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.eclipse.equinox.internal.ds.model.ServiceComponent.modified(ServiceComponent.java:310)
> 	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.modify(ServiceComponentProp.java:187)
> 	at org.eclipse.equinox.internal.ds.InstanceProcess.modifyComponent(InstanceProcess.java:690)
> 	at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationChange(SCRManager.java:523)
> 	at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationEvent(SCRManager.java:385)
> 	at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationEvent(SCRManager.java:303)
> 	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:91)
> 	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
> Caused by: org.eclipse.kura.KuraException: The configuration attribute clientId is required and no value has been specified.
> 	at org.eclipse.kura.core.util.ValidationUtil.notEmptyOrNull(ValidationUtil.java:37)
> 	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:685)

**Comment by dwoodard1** [comment] 2016-11-16 17:45
Did you get this error strictly working with the web UI? If no client-id is specified in the UI, the default behavior is to use the MAC address of the primary network interface.

**Comment by pablochacin** [comment] 2016-11-18 09:43
I have only tried it using the web UI.

**Comment by ctron** [comment] 2016-11-18 10:15
This error pops up for me every time you start up a fresh Kura

**Comment by dwoodard1** [comment] 2016-11-18 13:57
@ctron I have seen that error as well, but I think it is a different error. This seems to be happening after a configuration is passed to MqttDataTransport.

@pablochacin What Kura version and hardware are you using?

**Comment by ctron** [comment] 2016-11-18 16:28
Oh ok. I thought it is the error which pops up when starting.

**Comment by pablochacin** [comment] 2016-11-25 10:04
@dwoodard1  I'm using Kura 2.0.2 on a Docker container, based on the [raspberry-pi installer.](https://www.eclipse.org/downloads/download.php?file=/kura/releases/2.0.2/kura_2.0.2_raspberry-pi_installer.deb)

I can confirm that after modifying the default configuration to connect on startup without setting the client id produces the same error:

```
Caused by: org.eclipse.kura.KuraException: The configuration attribute clientId 
is required and no value has been specified.
	at org.eclipse.kura.core.util.ValidationUtil.notEmptyOrNull(ValidationUt
il.java:37)
	at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConf
iguration(MqttDataTransport.java:685)

```

**Comment by MMaiero** [comment] 2016-11-25 10:40
Hi @pablochacin, I would suggest you to use the nn installer for [raspberry-pi](https://www.eclipse.org/downloads/download.php?file=/kura/releases/2.0.2/kura_2.0.2_raspberry-pi-nn_installer.deb) or [raspberry-pi-2](https://www.eclipse.org/downloads/download.php?file=/kura/releases/2.0.2/kura_2.0.2_raspberry-pi-2-nn_installer.deb) inside your docker container: in that particular environment you don't need the full network management and firewall features that Kura provides. 
At the other side, like in this case, using such features in docker could cause issues.

**Comment by pablochacin** [comment] 2016-11-25 12:01
Hi @MMaiero  I suppose you mean this kind of errors

```
2016-11-25 10:48:03,974 [EthernetMonitor_enp0s31f6] WARN  o.e.k.n.a.m.EthernetMo
nitorServiceImpl - Error during Ethernet Monitor
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOExceptio
n: Cannot run program "ifdown": error=2, No such file or directory
```
I confirm that with the nn installer these errors are not present in the log.

**Comment by pablochacin** [comment] 2016-11-25 12:03
@dwoodard1  I injected the client-id in the default configuration modifying the snapshot_0.xml (it's not present) and the problem is fixed. Therefore, the problem is that the parameter is required and not set by default.

**Comment by MMaiero** [comment] 2016-11-25 12:16
@pablochacin Exactly.
The nn profile uses so called "emulator" bundles that, if not specified, fetch the client id using java primitives to get the mac address of the primary interface. 
The Kura build, with network and firewall enabled, uses a different approach and that can cause some issues, as you have seen.
I've just created and tried a docker container based on debian:jessie-backports where I've installed kura 2.0.2-nn and I see no issues with the client-id.

**Comment by pablochacin** [comment] 2016-12-01 13:58
@MMaiero  The problem with the client-id persists using nm version. However, now I see this message: "Framework is not running in emulation mode", do I need to setup something to launch Kura in emulator mode?  

Please take into consideration that the DataService is configure to auto-connect at startup time. I'm not using the web interface to connect the device.

**Comment by MMaiero** [comment] 2016-12-01 14:04
> The problem with the client-id persists using **nm** version.

if you are running Kura in a docker container you must use no-network (**nn**) version

**Comment by pablochacin** [comment] 2016-12-01 14:09
Sorry for the typo, that's what I meant in my previous post. I0m using the nn version
`kura_2.0.2_raspberry-pi-nn_installer.deb`

**Comment by dwoodard1** [comment] 2016-12-01 14:16
@MMaiero I have seen this error as well. I haven't looked into it, but I am guessing it is related to #823

**Comment by cdealti** [comment] 2017-05-26 08:31
Closing this as it's a duplicate of #823.

**Closed by cdealti** 2017-05-26 08:31 UTC
Labels: discussion, duplicate, kura-cloud
