### ISSUE TITLE
Snapshot problem on wires

### ISSUE THREAD

**Issue by aabramo** [eclipse/kura#1435] opened 2017-06-06 14:52 UTC
If for some reason (i.e. a change of a package name of a wire component already present in a snapshot) the web browser cannot reload the snapshot, a GWT exception is generated.
In such a case, a previuos consistent snapshot should be reloaded instead, possibily up to snapshot_0.

**Comment by dwoodard1** [comment] 2017-06-07 20:42
I can confirm this is an issue. For me, steps to re-create the problem are:

1. Create a Wire component and give it a name
2. Since the name can't be edited, delete the component
3. Add a new component of the same type with the corrected name

The Wire graph will behave as expected, but the graph cannot be displayed in the UI (GWT Error).

**Comment by MMaiero** [comment] 2017-06-12 07:53
@dwoodard1 Which component did you use? Any save in the middle of the steps? I've tried with a nightly from develop both using a timer and an asset, but I was not able to recreate the issue.

**Comment by MMaiero** [comment] 2017-06-12 08:35
I've created #1445 that could mitigate the issue.

**Comment by dwoodard1** [comment] 2017-06-12 15:46
@MMaiero This happened to me with the Modbus Driver asset. I will try and re-create then test your fix.

**Comment by cdealti** [comment] 2017-06-20 08:17
@aabramo can you please build the develop branch and check if #1445 makes any difference?

**Comment by MMaiero** [comment] 2017-06-29 07:43
@dwoodard1 Any update on this?

**Comment by dwoodard1** [comment] 2017-06-30 21:05
@MMaiero I believe the usability is better, but there is still an issue. Steps to reproduce (note - I am using the emulator and ModbusPal):

* Install the Modbus driver
* Create a simple Wire Graph consisting of a Timer and Asset. The Asset should use the Modbus driver. Name the Asset "ModbusAsset". Save the graph.
* Delete the Asset. Add a new Asset using the Modbus driver and name it "modbusAsset". Save the graph.
* Leave the Wire Graph editor and then return. You will see an error like:
![image](https://user-images.githubusercontent.com/1392274/27753941-b0c5458e-5d9c-11e7-90b5-8d0fc11ea8d8.png)

The intention of the above steps is to be able to change the name of an Asset. I would think the easiest thing would be to make the name editable. Having to delete and re-add the asset is not ideal, especially if the Asset has many channels. I am happy to close this issue and open a new if you agree that a user should be able to edit a Wire Component name.

**Comment by MMaiero** [comment] 2017-07-04 13:07
I see what you mean. The issue do not happen if, between deleting and creating a new component, you perform a save. I believe that was the original process idea that Amit coded.

I will try to see how to fix temporary this issue, but I agree with you that giving the possibility to rename a component would be the best.
But probably it will not be an easy task to perform since the name is used as kura.service.pid and renaming would require destroying a component and creating another with the same properties.

**Comment by cdealti** [comment] 2017-07-13 10:43
@dwoodard1 @MMaiero 

> Create a simple Wire Graph consisting of a Timer and Asset. The Asset should use the Modbus driver. Name the Asset "ModbusAsset". Save the graph.
> Delete the Asset. Add a new Asset using the Modbus driver and name it "modbusAsset". Save the graph.

Is the case ("ModbusAsset" -> "modbusAsset") relevant for this issue?

**Comment by cdealti** [comment] 2017-07-18 17:33
@dwoodard1 please complete review #1494

**Comment by dwoodard1** [comment] 2017-07-20 15:23
Closing via #1494

**Closed as completed by dwoodard1** 2017-07-20 15:23 UTC
Labels: bug, kura-wires
