### ISSUE TITLE
[Watchdog Service] Reboot cause may become stale

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1838] opened 2017-12-18 15:48 UTC
The reboot cause may not be the one for the latest reboot. Ignore the issue if that's the intended behavior.

#1575 demanded adding a cause to every reboot started by Watchdog Service. This cause is created the first time but never again as the file existence is checked and contents is never replaced.
If #1418 is fully implemented, the reboot cause file can be deleted after it served its purpose, so that a new one can be written before the next service-triggered reboot. The other option is to maybe remove the existing file check.

Test scenario (or just run unit tests):
1. remove /opt/eclipse/kura/data/kura-reboot-cause
1. configure one of the critical components for failure
1. enable Watchdog Service
1. wait for reboot
1. remember cause file contents
1. wait for another reboot
1. compare cause file contents to the previous one

Kura 3.2.0-SNAPSHOT on RPi3

**Comment by MMaiero** [comment] 2018-01-18 09:12
@markoer I would say that this is the intended behaviour for the current implementation.

**Comment by markoer** [comment] 2018-01-18 09:19
OK, then.

**Comment by MMaiero** [comment] 2018-01-24 11:37
Closing this issue for now

**Closed as completed by MMaiero** 2018-01-24 11:37 UTC
