### ISSUE TITLE
[Kura 3.0.0 M1 QA] RPi 2/3 installation package contains unwanted files

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#1104] opened 2017-02-16 12:09 UTC
RPi 2 installation contains
* plugins/org.junit_4.12.0.v201504281640.jar (regression of #860)
* install/network.interfaces.intel.edison - only intended for Edison, probably

Excludes concerning JUnit also contain com.gwt.user_*, but I also found plugins/com.gwt.user_1.0.1-SNAPSHOT.jar in installation.

RPi 3, kura 3.0.0-SNAPSHOT build 940

**Comment by MMaiero** [comment] 2017-02-16 12:59
I think that the org.junit is a regression, probably due to the changes to the build done by Jens.
I'm fixing that now.

In install folder we place many different files, the kura_install.sh based on them installs what expected for the desired platform.
Why are you concerned by com.gwt.user?

**Comment by markoer** [comment] 2017-02-16 13:59
I'm not concerned about com.gwt.user_*, but it's specified in some of the excludes where JUnit is. If it's OK, don't worry about it.

**Comment by MMaiero** [comment] 2017-02-16 14:02
That was excluded to have the inclusion in another point of the code.

**Comment by MMaiero** [comment] 2017-02-16 14:03
Please have a look at #1108.

**Comment by markoer** [comment] 2017-02-16 16:12
Local build (.zip) doesn't contain the junit jar with this change. I will also check the CI build once you merge it and it's available.

**Comment by MMaiero** [comment] 2017-02-17 09:05
I've checked the build in Hudson and the fix seems working well. Closing.

**Closed as completed by MMaiero** 2017-02-17 09:05 UTC

**Comment by markoer** [comment] 2017-02-17 11:33
I checked build 942 and it's OK.
