### ISSUE TITLE
great difficulties with kura installation

### ISSUE THREAD

**Issue by marentwickler** [eclipse/kura#1346] opened 2017-04-24 19:18 UTC
I find great difficulties with kura installation,I use eclipse Installer .I can't to build kura project by installing, the issue is :' Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location ...... No repository found at file://..../ iot-kura-develop/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository. -> [Help 1]'.
![screen shot 2017-04-24 at 00 07 11](https://cloud.githubusercontent.com/assets/11528983/25354479/fdcb54dc-292a-11e7-9dfc-d5bee36cd35a.png)
Thanks in advance

**Comment by nicolatimeus** [comment] 2017-04-26 07:58
Hi,

I have tested the Oomph installer, and I can confirm the issue. It is a temporary problem caused by the fact that the mirror that provides the Equinox package for the build does not work.

This causes the build of the `develop` branch (the one that is used by the Oomph installer) to fail, because the `p2-repo-equinox_3.11.1` local repository cannot be created.

This issue has already been fixed on the `release-3.0.0` branch, the fix will be merged back to `develop` when Kura 3.0.0 is released.

For the time being you can try running the installer again using this setup file, it should give you a working Developer environment based on the `release-3.0.0` branch:

https://raw.githubusercontent.com/nicolatimeus/kura/fix_oomph-setup/kura/setups/kura.setup

Before running the installer, clear the cache of the Oomph installer executing the following command in a terminal:

`rm -rf $HOME/.eclipse/org.eclipse.oomph.*`

Regards

**Comment by MMaiero** [comment] 2017-04-27 08:31
I think we can close now.

**Comment by cdealti** [comment] 2017-04-28 13:01
Reopening this because it must be fixed. What if one wants the installer for the KURA_3.0.0_RELEASE tag?

**Comment by diegovisentin** [comment] 2017-05-04 00:42
Hi, 
on a brand new installation made via oomph and based on "release-3.0.0" branch, the only way to resolve all errors in Eclipse has been to run "build-all.sh" script. 
But the emulator doesn't work :-(
Could you be so kind to give me some tips to fix this?

Thanks, Diego

**Comment by nicolatimeus** [comment] 2017-05-04 09:53
Hi,

Which operating system are you using for development? We tested the Oomph installer on OSX and Linux and it seems to be working. The Windows platform is currently unsupported as development environment.

The fact that after the initial build Eclipse still reports errors for some projects shouldn't be harmful, the errors are related to the fact that Eclipse is unable to discover lifetime mappings for some Maven plugins. The important thing is that the initial build completes without errors, if the initial build is failing on your machine, please post the log.

Concerning the emulator, you will find several launch configurations in the workspace, the `Eclipse Kura Emulator` one should work.

You can select it performing the following steps:

1. Select **Run** -> **Run Configurations** from the Eclipse menu, a new window should appear.
2. Select **OSGi Famework** -> **Eclipse Kura Emulator** in the left panel, and click the **Run** button.

**Comment by diegovisentin** [comment] 2017-05-04 12:15
I'm using OpenSUSE (fixed at last level ;->).
Just for your information, I followed the steps descried in "For the Eclipse Installer based setup" of "Getting_Started" wiki page.

**Comment by nicolatimeus** [comment] 2017-05-04 12:55
Can you please try to perform a clean installation again?

Remove the previous Eclipse installation and then run the installer using the setup file posted above instead of the one specified in the Getting Started guide:

https://raw.githubusercontent.com/nicolatimeus/kura/fix_oomph-setup/kura/setups/kura.setup

Before doing that make sure to clean the cache of the Oomph installer:

`rm -rf $HOME/.eclipse/org.eclipse.oomph.*`

Eclipse will perform a full Maven build at startup, you can follow its progress in the console, wait for it to finish and then try running the emulator as shown above.

If anything fails please provide some more details so that we can figure out what is going wrong.

**Comment by marentwickler** [comment] 2017-05-04 21:57
Hi, and thanks for your interactions ,

I've also gone the same way for kura setup from "Getting_Started" wiki page, but today I have restarted eclipse, then I lost kura-emulator.
I try again to install kura , How can I use Started guide with Oomph installer?
https://raw.githubusercontent.com/nicolatimeus/kura/fix_oomph-setup/kura/setups/kura.setup.
Kura installation costs a lot of time.
in kura/github i get kura.setup for old version not for release-3.0.0.

Thanks in advance

**Comment by ctron** [comment] 2017-05-05 09:38
@marentwickler Could you try to setup up Kura in develop and then switch the branch to release-3.0.0?

**Comment by marentwickler** [comment] 2017-05-05 12:05
Hi all,
I tried kura to install with Oomph installer  and kura.setup from release-3.0.0 ,the building is successful, But I got this issues:
'Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:properties-maven-plugin:1.0-alpha-1:read-project-properties (execution: read-previous-release-versions, phase: initialize)	pom.xml	/org.eclipse.kura.api	line 48	Maven Project Build Lifecycle Mapping Problem ......'.
I can't run kura!.
![screen shot 2017-05-05 at 13 01 26](https://cloud.githubusercontent.com/assets/11528983/25744664/06a15d8e-3193-11e7-97ed-9a92c40a6f89.png)
![screen shot 2017-05-05 at 13 04 18](https://cloud.githubusercontent.com/assets/11528983/25744768/7a889e10-3193-11e7-8416-a0cc0cfb8c41.png)

Thanks in advance

**Comment by ctron** [comment] 2017-05-05 12:14
Seems like some missing m2e declarations. You can ignore those errors, or "fix" them with the Quick fix, marking them as ignored.

**Comment by amitjoy** [comment] 2017-05-05 16:06
As far as I remember, I also encountered such issue and got it resolved by installing `Tycho m2e Connector` from `Eclipse Preferences->Maven->Discovery->Open Catalog`

**Comment by marentwickler** [comment] 2017-05-05 20:39
Hi,
only two issues, 
one is refers to package  org.eclipse.kura.protocol.can ,the packege  
![screen shot 2017-05-05 at 21 20 35](https://cloud.githubusercontent.com/assets/11528983/25763400/cb5655c0-31da-11e7-9dec-8f47c62520ac.png)
libsocket-can-java.jar is not in lib from org.eclipse.kura.protocol.can What is problematic for building, 
![screen shot 2017-05-05 at 21 20 35](https://cloud.githubusercontent.com/assets/11528983/25763465/2fd88630-31db-11e7-8332-2581a22668df.png)



second:
Project build error: Non-resolvable parent POM for org.eclipse.kura:org.eclipse.kura.qa:1.0.100-SNAPSHOT: Could not find artifact org.eclipse.kura:kura:pom:3.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM	pom.xml	/org.eclipse.kura.qa	line 19	Maven pom Loading Problem

(https://cloud.githubusercontent.com/assets/11528983/25763441/0f321176-31db-11e7-916e-b5534f5fdbd3.png)

**Comment by marentwickler** [comment] 2017-05-06 06:34
hi,
Kura Emulator not work:
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.kura.emulator [3]
  Unresolved requirement: Import-Package: org.apache.commons.io; version="2.4.0".

Every project missing something!

org.osgi.framework.BundleException: Could not resolve module: org.eclipse.kura.test [2]
  Unresolved requirement: Import-Package: junit.framework.


!ENTRY org.eclipse.osgi 4 0 2017-05-06 07:25:19.377
!MESSAGE Bundle initial@reference:file:../../../git/kura/kura/emulator/org.eclipse.kura.emulator/ was not resolved.

!ENTRY org.eclipse.osgi 4 0 2017-05-06 07:25:19.376
!MESSAGE Bundle initial@reference:file:../../../git/kura/kura/test/org.eclipse.kura.test/ was not resolved.

!ENTRY org.eclipse.osgi 4 0 2017-05-06 07:25:19.378
!MESSAGE Could not find bundle: org.eclipse.equinox.console
!STACK 0
.
.
.
.
.!!

**Closed as completed** 2017-05-07 21:44 UTC
Labels: bug, kura-devenv

**Comment by diegovisentin** [comment] 2017-05-08 07:24
@marentwickler thanks for your hints.
Unlike my previous attempts, the cache cleanup and the use of the "Eclipse Kura Emulator" seems to have solved the problems. Therefore in next days I'll do other tests.
Thanks a lot for the support.
