### ISSUE TITLE
[Kura 2.1.0 QA] NET-ETH0-014 Wrong lease time in DHCP mode

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#948] opened 2016-12-15 11:03 UTC
I did leave the default lease time of 7200. However the following is being reported by my local machine:

```
Dec 15 11:58:11 jreimann dhclient[22873]: DHCPOFFER from 192.168.1.1
Dec 15 11:58:11 jreimann dhclient[22873]: DHCPACK from 192.168.1.1 (xid=0x44a86bdd)
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2):   address 192.168.1.10
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2):   plen 24 (255.255.255.0)
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2):   gateway 192.168.1.1
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2):   server identifier 192.168.1.1
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2):   lease time 26597835
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2):   nameserver '192.168.1.1'
Dec 15 11:58:11 jreimann NetworkManager[1099]: <info>  [1481799491.1377] dhcp4 (enp0s20f0u2): state changed unknown -> bound

```

**Comment by cdealti** [comment] 2016-12-15 14:01
I'd like to take a look before deciding the milestone. Can you please send me ``/etc/dhcpd-eth0.conf``?

**Comment by ctron** [comment] 2016-12-15 14:48
```
# enabled? true
# prefix: 24
# pass DNS? true

subnet 192.168.1.0 netmask 255.255.255.0 {
    option domain-name-servers 192.168.1.1;

    interface eth0;
    option routers 192.168.1.1;
    default-lease-time 7200;
    max-lease-time 7200;
    pool {
        range 192.168.1.10 192.168.1.20;
    }
}
```

**Comment by MMaiero** [comment] 2017-04-24 08:08
@markoer Could you please have a look and confirm if this is an issue also for you? Thanks

**Comment by markoer** [comment] 2017-06-08 09:30
I tried it with Kura 3.0.0 (as well as before) and didn't experience this problem.

**Comment by MMaiero** [comment] 2017-06-08 09:47
@ctron Could you please check if this issue is still there for you? Otherwise, I think we can close.

**Comment by MMaiero** [comment] 2017-06-23 10:40
Closing for now. We can reopen it later if during next QA we will find that the issue is there.

**Closed by MMaiero** 2017-06-23 10:40 UTC
Labels: bug, kura-net
