### ISSUE TITLE
Apply Button Always Enabled in Network

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse/kura#2724] opened 2020-03-26 13:50 UTC
If you navigate to Network tab, you will see that the Apply button is always enabled, although user does not change anything, which is not the desired behvaiour. 

**Testflow:**
1. Login to Kura as admin/admin
2. Go to Network, without changing anything try to press Apply button
3. Apply button is clickable, and it looks like Kura saves something, but really doesn't.

**Expected behavior**
Apply button should be activated only when user makes some changes. 

**Screenshots**
![Screenshot 2020-03-26 at 14 27 43](https://user-images.githubusercontent.com/15121999/77654085-df347a00-6f70-11ea-9fda-411e7141921e.png)

Target Environment (please complete the following information):
Board: Raspberry Pi 3
OS version: Linux raspberrypi 4.19.75-v7+ # 1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Additional info: /

**Comment by MMaiero** [comment] 2020-06-18 06:56
I believe this is a duplicate of #2873

**Comment by LeoNerdoG** [comment] 2020-06-18 07:04
Hey @MMaiero,
you are right. I will close #2873 as duplicate.

**Closed as completed** 2020-09-23 10:29 UTC
Labels: enhancement, P2, help wanted
