### ISSUE TITLE
[Configuration] Greenhouse demo not properly tracked by the Configuration Service

### ISSUE THREAD

**Issue by cdealti** [eclipse/kura#536] opened 2016-09-12 10:44 UTC
Affected releases: Kura >= 2.0.0

> Hello,
>
> Here is a summary of what I have found. There may be something obvious in the Greenhouse demo that I am missing, but I would be curious as to why it worked in Kura < 2.0.
>
> 1. This does not affect all DPs. For example, the SensorTag DP works as expected.
> 2. The DP that does not work can be found here [1] and source code here [2].
> 3. When the DP is installed in Kura for the first time, the PID is null. If you check the SCR through the console, the property is present.
> 4. If you uninstall the DP and install it again, it works. The log output of this install->uninstall->install is below.
> 5. When I downloaded the DP to my laptop and installed, instead of using the URL, I see a slightly different behavior. The null PID exists on first install, but when I uninstall, the ConfigurableComponentTracker does not remove the component. So, the uninstall/re-install method does not work. I can produce logs for this too if interested.
> 6. None of the above affects the running of the bundle(s) in the framework. All bundles and components start and run as expected.
>
> 2016-09-08 19:11:02,337 [qtp21986801-34] INFO  o.e.k.w.s.s.FileServlet - Installing package...
> 2016-09-08 19:11:02,339 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - About to install package at URL http://iot.eclipse.org/java/demo/org.eclipse.greenhouse.iot-0.1.0.dp
> 2016-09-08 19:11:11,260 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering metatype pid: org.eclipse.iot.greenhouse.publisher.GreenhousePublisher with ocd: org.eclipse.kura.core.configuration.metatype.Tocd@761537 ...
> 2016-09-08 19:11:11,262 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Merging configuration for pid: org.eclipse.iot.greenhouse.publisher.GreenhousePublisher
> 2016-09-08 19:11:15,553 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Seeding updated configuration for pid: org.eclipse.iot.greenhouse.publisher.GreenhousePublisher
> 2016-09-08 19:11:15,560 [Component Resolve Thread (Bundle 7)] INFO  o.e.i.g.p.GreenhousePublisher - Activating GreenhousePublisher... Done.
> 2016-09-08 19:11:15,562 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurableComponentTracker - Adding ConfigurableComponent with pid null, service pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher and factory pid null
> 2016-09-08 19:11:15,562 [Component Resolve Thread (Bundle 7)] WARN  o.e.k.c.c.ConfigurationServiceImpl - Either kura.service.pid null or service.pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher are null
> 2016-09-08 19:11:15,652 [Component Resolve Thread (Bundle 7)] INFO  o.e.i.g.c.GreenhouseCoapServer - Activating GreenhouseCoapServer...
> 2016-09-08 19:11:15,814 [Component Resolve Thread (Bundle 7)] INFO  o.e.i.g.c.GreenhouseCoapServer - Activating GreenhouseCoapServer... Done.
> 2016-09-08 19:11:15,867 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - Posting INSTALLED event for package at URL http://iot.eclipse.org/java/demo/org.eclipse.greenhouse.iot-0.1.0.dp: successful
> 2016-09-08 19:11:25,849 [DeploymentAgent:Uninstall] INFO  o.e.k.d.a.i.DeploymentAgent - About to uninstall package 
> 2016-09-08 19:11:25,913 [DeploymentAgent:Uninstall] INFO  o.e.k.c.c.ConfigurableComponentTracker - Removed ConfigurableComponent with pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher and service pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher
> 2016-09-08 19:11:25,915 [DeploymentAgent:Uninstall] INFO  o.e.k.c.c.ConfigurationServiceImpl - Removing component configuration for pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher
> 2016-09-08 19:11:25,932 [DeploymentAgent:Uninstall] INFO  o.e.i.g.s.r.Pi4JGreenhouseSensorService - Deactivating Pi4JGreenhouseSensorService...
> 2016-09-08 19:11:25,933 [DeploymentAgent:Uninstall] INFO  o.e.i.g.s.r.Pi4JGreenhouseSensorService - ... unexport all GPIOs
> 2016-09-08 19:11:25,940 [DeploymentAgent:Uninstall] INFO  o.e.i.g.s.r.Pi4JGreenhouseSensorService - ... shutdown
> 2016-09-08 19:11:25,950 [DeploymentAgent:Uninstall] INFO  o.e.i.g.s.r.Pi4JGreenhouseSensorService - ... DONE.
> 2016-09-08 19:11:25,953 [DeploymentAgent:Uninstall] INFO  o.e.i.g.s.r.Pi4JGreenhouseSensorService - Deactivating Pi4JGreenhouseSensorService... Done.
> 2016-09-08 19:11:26,051 [DeploymentAgent:Uninstall] INFO  o.e.k.d.a.i.DeploymentAgent - Posting UNINSTALLED event for package org.eclipse.iot.greenhouse: successful
> 2016-09-08 19:11:34,658 [DnsMonitorServiceImpl] WARN  o.e.k.n.a.m.DnsMonitorServiceImpl - Not Setting DNS servers to empty
> 2016-09-08 19:11:53,230 [qtp21986801-33] INFO  o.e.k.w.s.s.FileServlet - Installing package...
> 2016-09-08 19:11:53,231 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - About to install package at URL http://iot.eclipse.org/java/demo/org.eclipse.greenhouse.iot-0.1.0.dp
> 2016-09-08 19:11:55,310 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registering metatype pid: org.eclipse.iot.greenhouse.publisher.GreenhousePublisher with ocd: org.eclipse.kura.core.configuration.metatype.Tocd@46b401 ...
> 2016-09-08 19:11:55,854 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Seeding updated configuration for pid: org.eclipse.iot.greenhouse.publisher.GreenhousePublisher
> 2016-09-08 19:11:55,860 [Component Resolve Thread (Bundle 7)] INFO  o.e.i.g.p.GreenhousePublisher - Activating GreenhousePublisher... Done.
> 2016-09-08 19:11:55,863 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurableComponentTracker - Adding ConfigurableComponent with pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher, service pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher and factory pid null
> 2016-09-08 19:11:55,863 [Component Resolve Thread (Bundle 7)] INFO  o.e.k.c.c.ConfigurationServiceImpl - Registration of ConfigurableComponent org.eclipse.iot.greenhouse.publisher.GreenhousePublisher by org.eclipse.kura.core.configuration.ConfigurationServiceImpl@e58119...
> 2016-09-08 19:11:55,997 [Component Resolve Thread (Bundle 7)] INFO  o.e.i.g.c.GreenhouseCoapServer - Activating GreenhouseCoapServer...
> 2016-09-08 19:11:56,176 [Component Resolve Thread (Bundle 7)] INFO  o.e.i.g.c.GreenhouseCoapServer - Activating GreenhouseCoapServer... Done.
> 2016-09-08 19:11:56,212 [DeploymentAgent] INFO  o.e.k.d.a.i.DeploymentAgent - Posting INSTALLED event for package at URL http://iot.eclipse.org/java/demo/org.eclipse.greenhouse.iot-0.1.0.dp: successful
>
>
> [1] http://iot.eclipse.org/java/demo/org.eclipse.greenhouse.iot-0.1.0.dp
> [2] https://github.com/kartben/kura-greenhouse-demo

**Comment by cdealti** [comment] 2016-09-15 09:31
@dwoodard1 The root cause of this is that the ``org.eclipse.iot.greenhouse.publisher.GreenhousePublisher`` component has ``configuration-policy = optional``. This is perfectly legal but it's not common for a Kura ``ConfigurableComponent``.

This is a regression introduced with Kura 2.0.0.
The problem is that the Kura ``ConfigurationServiceImpl`` assumes that the property ``kura.service.pid`` introduced with Kura 2.0.0 is always present.

If this property is not set in the component definition the ``ComponentMetatypeBundleTracker`` will set it to the value of ``service.pid`` and will update the component configuration.
If the component has ``configuration-policy = required`` it will become satisfied and it will activate with ``kura.service.pid`` properly set and ``ConfigurationServiceImpl`` will properly track it.

Otherwise, If the component has ``configuration-policy = optional``, the component might activate before its configuration is updated by ``ComponentMetatypeBundleTracker``. The ConfigurationServiceImpl will not find ``kura.service.pid`` ignoring the component and printing a warning:

```
2016-09-08 19:11:15,562 [Component Resolve Thread (Bundle 7)] WARN o.e.k.c.c.ConfigurationServiceImpl - Either kura.service.pid null or service.pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher are null
```

There are two workarounds:
1. In the ``org.eclipse.iot.greenhouse.publisher.GreenhousePublisher`` component definition set ``configuration-policy = required``
2. In the ``org.eclipse.iot.greenhouse.publisher.GreenhousePublisher`` component definition add a new ``kura.service.pid`` and set it to  ``org.eclipse.iot.greenhouse.publisher.GreenhousePublisher``

**Comment by dwoodard1** [comment] 2016-09-15 16:19
Thanks for finding the cause of the problem. It seems we should address this as configuration-policy = optional should be allowed, even when implementing ConfigurableComponent. Wouldn’t you agree?


On Sep 15, 2016, at 05:31, Cristiano De Alti <notifications@github.com<mailto:notifications@github.com>> wrote:


@dwoodard1<https://github.com/dwoodard1> The root cause of this is that the org.eclipse.iot.greenhouse.publisher.GreenhousePublisher component has configuration-policy = optional. This is perfectly legal but it's not common for a Kura ConfigurableComponent.

This is a regression introduced with Kura 2.0.0.
The problem is that the Kura ConfigurationServiceImpl assumes that the property kura.service.pid introduced with Kura 2.0.0 is always present.

If this property is not set in the component definition the ComponentMetatypeBundleTracker will set it to the value of service.pid and will update the component configuration.
If the component has configuration-policy = required it will become satisfied and it will activate with kura.service.pid properly set and ConfigurationServiceImpl will properly track it.

Otherwise, If the component has configuration-policy = optional, the component might activate before its configuration is updated by ComponentMetatypeBundleTracker. The ConfigurationServiceImpl will not find kura.service.pid ignoring the component and printing a warning:

2016-09-08 19:11:15,562 [Component Resolve Thread (Bundle 7)] WARN o.e.k.c.c.ConfigurationServiceImpl - Either kura.service.pid null or service.pid org.eclipse.iot.greenhouse.publisher.GreenhousePublisher are null


There are two workarounds:
1. In the org.eclipse.iot.greenhouse.publisher.GreenhousePublisher component definition set configuration-policy = required
2. In the org.eclipse.iot.greenhouse.publisher.GreenhousePublisher component definition add a new kura.service.pid and set it to org.eclipse.iot.greenhouse.publisher.GreenhousePublisher

**Comment by cdealti** [comment] 2016-09-15 16:26
I sadly agree. I've opened #547 to track this bug.

**Comment by MMaiero** [comment] 2016-10-21 08:23
Closing in favor of #547

**Closed by MMaiero** 2016-10-21 08:23 UTC
Labels: bug, kura-config
