### ISSUE TITLE
[Core] Linux primary network interface name

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#632] opened 2016-10-14 09:06 UTC
When running org.eclipse.kura.core.test bundle tests on the current develop branch HEAD the following exception occurs on CentOS 7 Linux:

```
java.lang.IllegalStateException: Invalid MQTT client configuration
        at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:775)
        at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.update(MqttDataTransport.java:263)
        at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.onConfigurationUpdated(MqttDataTransport.java:673)
        at org.eclipse.kura.core.ssl.SslServiceListeners.onConfigurationUpdated(SslServiceListeners.java:38)
        at org.eclipse.kura.core.ssl.SslManagerServiceImpl.updated(SslManagerServiceImpl.java:161)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.modified(ServiceComponent.java:310)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.modify(ServiceComponentProp.java:187)
        at org.eclipse.equinox.internal.ds.InstanceProcess.modifyComponent(InstanceProcess.java:690)
        at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationChange(SCRManager.java:523)
        at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationEvent(SCRManager.java:352)
        at org.eclipse.equinox.internal.ds.SCRManager.processConfigurationEvent(SCRManager.java:303)
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:91)
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: org.eclipse.kura.KuraException: The configuration attribute clientId is required and no value has been specified.
        at org.eclipse.kura.core.util.ValidationUtil.notEmptyOrNull(ValidationUtil.java:34)
        at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.buildConfiguration(MqttDataTransport.java:696)
        ... 16 more
```

I traced the origin of the exception to `MqttDataTransport.buildConfiguration()`. This method then calls

```
if (clientId == null || clientId.trim().length() == 0) {
    clientId = this.m_systemService.getPrimaryMacAddress();
}
```

`SystemServiceImpl.getPrimaryMacAddress()` calls `getPrimaryNetworkInterfaceName()`. This last method hardcodes eth0 as the network interface used in Linux. But according to [PredictableNetworkInterfaceNames](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) eth0 is no longer the first network device on some newer Linux distributions.

Possible workarounds (or maybe the proper solutions) when running on such distros are: 
- add a line similar to

```
kura.primary.network.interface=ens32
```

(replace ens32 with the appropriate interface name) to `emulator/org.eclipse.kura.emulator/src/main/resources/kura.properties`
- add a line similar to

```
kura.primary.network.interface=ens32
```

to `org.eclipse.kura.core.test/src/main/resources/kura_custom.properties`

A similar configuration is probably necessary elsewhere when running Kura outside of test environment.

**Comment by cdealti** [comment] 2016-10-14 10:36
@markoer Thanks. This has also been reported for #568.

**Comment by cdealti** [comment] 2017-05-26 10:33
Closing as duplicate of #823.

**Closed by cdealti** 2017-05-26 10:33 UTC
Labels: duplicate
