### ISSUE TITLE
Modbus write to asset channel problem

### ISSUE THREAD

**Issue by mgogic** [eclipse/kura#1983] opened 2018-03-23 11:51 UTC
Component affected:

- Component affected:
  - [ ] Distribution
    - Installer name (e.g. kura_3.1.0_raspberry-pi-2-3_installer.deb): Kura_3.2.0-SNAPSHOT_raspberry-pi-2-3_installer.deb
    - Platform (e.g. Raspberry pi 2): Raspberry pi 3
    - Kura version affected (e.g. Kura 3.1.0): 3.2.0
    - Java version (paste the result of **java -version**: openjdk 1.8.0_40-internal
    - Host OS (e.g. Debian): Raspbian
    - Host OS version : 8 (jessie)

Textual description of the issue:

Is it possible to perform Modbus write to single asset channel?
When I try with ModbusPal 1.6b to write on single asset channel, write occures on all channels.

Regards,
Milan

**Comment by MMaiero** [comment] 2018-03-23 13:10
Hi,
could you please provide a description of the steps taken, in order to reproduce the issue? Are you using the asset in the wire composer or only in drivers and assets? In which way are you interacting with the asset?

Thanks.
Best regards,
Matteo

**Comment by mgogic** [comment] 2018-03-23 13:22
- First I installed com.eurotech.modbus.driver , version 1.0.101.
- Added two modbus drivers ( on first, I added two channels, on second one channel), and managed driver parameters (access.type, modbus.tcp-udp.ip, modbus.tcp-udp.port (1502), etc.)
- After that, I downloaded ModbusPal 1.6b and added one ModbusSlave (For Port option I used same port from drivers setup )
- Channels are all enabled,  type is READ_WRITE, value type is BOOLEAN, primary.table is COILS
- When I write into Data section of channels, I write ,for example, true in one channel, and write occures on all channels, all channels values are set to true.

**Comment by MMaiero** [comment] 2018-03-23 13:25
Yes, that tab does not perform checks on fields changed, but simply writes all the values. In any case, the APIs support the writing of a simple channel (wires too).
We can take this as a possible improvement of the Data tab in Drivers and Assets.
Thanks for reporting that.

Maybe someone is willing to contribute that change.

**Comment by markoer** [comment] 2018-03-26 10:49
As it turns out, Kura doesn't work properly if assets/channels are not configured properly (i.e. all channels point to the same memory location). After @mgogic reconfigured the channels, all was fine.
If you want to keep the issue as a UI enhancement, that's OK, otherwise please close it.

**Comment by MMaiero** [comment] 2018-03-26 11:56
Let's close it for the time being. We'll reopen it when needed.

**Closed as completed by MMaiero** 2018-03-26 11:56 UTC
Labels: enhancement, help wanted
