### ISSUE TITLE
Unable to deploy two DPs which share the same bundle

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#734] opened 2016-11-09 10:24 UTC
If you deploy two DPs which share the same bundle, the second DP will not be activated but fail with an exception. For example:

```2016-11-09 10:10:56,363 [DeploymentAgent] ERROR o.e.k.d.a.i.DeploymentAgent - Exception installing package at URL file:/tmp/de.dentrassi.kura.addons.neoscada_0.1.0-SNAPSHOT.dp
org.osgi.service.deploymentadmin.DeploymentException: Bundle 'com.google.guava/19.0.0 already present in other deployment packages!
        at org.apache.felix.deploymentadmin.DeploymentAdminImpl.verifyNoResourcesShared(DeploymentAdminImpl.java:594)
        at org.apache.felix.deploymentadmin.DeploymentAdminImpl.installDeploymentPackage(DeploymentAdminImpl.java:196)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.installDeploymentPackageInternal(DeploymentAgent.java:469)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.installer(DeploymentAgent.java:309)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent.access$0(DeploymentAgent.java:293)
        at org.eclipse.kura.deployment.agent.impl.DeploymentAgent$1.run(DeploymentAgent.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

I do know that, from an OSGi perspective, this "works as designed". But with Kura targeting the Eclipse Marketplace it may get difficult to get some addons working together.

I think we should look into the direction of something like OSGi subsystems which could be a fix for that.

**Comment by cdealti** [comment] 2016-11-09 10:29
This is expected and documented in the Deployment Admin spec.
If a bundle is already installed or is managed by the Deployment Admin as part of a different Deployment Package then what you describe above is correct.
Closing this because it's not a bug.

**Comment by ctron** [comment] 2016-11-09 13:38
I still think that we should somehow, in the future, support this. By having an alternative to the current deplyoment admin.

**Comment by cdealti** [comment] 2017-11-13 09:10
Closing again as there's no solution with deployment packages.

**Closed by cdealti** 2017-11-13 09:10 UTC
Labels: discussion
