### ISSUE TITLE
Re-compile with libudev.so.1

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#1014] opened 2017-01-16 15:28 UTC
To me it seems as if all target support `libudev.so.1`. So instead of maintaining two native variants I would suggest to drop support for `libudev.so.0` and switch to `libudev.so.1`.

**Comment by cdealti** [comment] 2017-03-15 10:03
@unverbraucht can you please check if you need to continue supporting libudev.so.0 for the PC engine distrib?

**Comment by dwoodard1** [comment] 2017-03-16 16:50
@jread Can you respond to the above comment from @cdealti ? We will start the QA process for Kura v3.0.0 in the coming weeks, so we need to make sure you can still QA the PC Engine distribution.

**Comment by unverbraucht** [comment] 2017-03-16 16:58
Hi guys,

the PC engines board is running Debian 8 in our setup so libudev.so.1 should be perfect.

**Comment by cdealti** [comment] 2017-05-26 08:19
@ctron duplicate of #1321?

**Closed as completed** 2017-06-23 10:03 UTC
Labels: duplicate, discussion
