### ISSUE TITLE
Factories don't get removed from creation dialog

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#2022] opened 2018-04-04 13:52 UTC
Using Kura 3.2 RC:

* Install "Example Publisher for Eclipse Kura" from the marketplace
* Open + Dialog, verify the factory ID is present
* Uninstall the example publisher
* Wait
* Reload the Web UI
* Open the + Dialog -> The factory ID is still present

**Comment by cdealti** [comment] 2018-04-04 16:10
@ctron as agreed in the weekly call we will evaluate a simple fix to the `ConfigurationService`.
If it turns out this is too hard the problem will be documented as a known issue in the release notes, as we always do.

Note that the factory ID goes away at the next Kura start.

**Comment by markoer** [comment] 2018-04-05 08:17
I believe this issue is a duplicate of #2015's alternative manifestation.

**Comment by cdealti** [comment] 2018-04-05 10:43
I don't think so. We know, by code inspection, that factories cached by the ConfigurationService are not removed.

**Comment by MMaiero** [comment] 2018-04-06 15:21
Merged. Let's wait a new RC and close the issue if the problem is solved

**Comment by MMaiero** [comment] 2018-04-12 10:06
It seems to be verified on the supported platforms. Let's close for now

**Closed as completed by MMaiero** 2018-04-12 10:06 UTC
Labels: bug, kura-config, Kura-3.2.0
