### ISSUE TITLE
[Kura 2.1.0 QA] Regression on GPIO example, parameters not correctly updated

### ISSUE THREAD

**Issue by pierrepitiot** [eclipse/kura#946] opened 2016-12-15 09:26 UTC
Testing [PTC-GPIO-004] on Reliagate 10-20 I was not able to modify correctly the configuration parameters for gpio.directions, gpio.modes and gpio.triggers. The values are not modified after the first set and a new value always give Direction=3, Mode=-1 and Trigger=-1.

This is a regression, the test is passing correctly on ESF 4.0.2

**Comment by ctron** [comment] 2016-12-15 12:44
Are we talking about Kura or ESF?

**Comment by MMaiero** [comment] 2016-12-15 12:50
Duplicate of #893

**Closed by MMaiero** 2016-12-15 12:50 UTC
Labels: bug, duplicate
