### ISSUE TITLE
URI has an authority component

### ISSUE THREAD

**Issue by rita-zgheib** [eclipse/kura#997] opened 2017-01-11 10:12 UTC
Hey,
I am trying to build kura project using this command "mvn -Dmaven.test.skip=true -f manifest_pom.xml clean install"
but I have the same problem always URI has an authority component  Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location file:////C:/Users/rzgheib/git/kura/kura/target-definition/equinox_3.11.1/repository/

Any advice?
Thank you in advance,

Rita

**Comment by dwoodard1** [comment] 2017-01-11 21:56
I don't have a Windows machine to test on, but it looks like an extra "/" may have been added to the manifest_pom.xml file. Can you try changing:

file:////${kura.basedir}/target-definition/equinox_3.11.1/repository/

to 

file:///${kura.basedir}/target-definition/equinox_3.11.1/repository/

@pierrepitiot Do you have a Windows machine on which you could try building the develop branch?

**Comment by rita-zgheib** [comment] 2017-01-12 14:07
I tried to remove "/" and I tried all "/" options but it doesn't work. I followed the documentation and instructions in this link: https://wiki.eclipse.org/Kura/Getting_Started

It seems that it is a problem with equinox 3.11.1 because I found another version with kura-equinox_3.8.1 and it works. I am now following this documentation https://eclipse.github.io/kura/doc/kura-setup.html and i downloaded Kura with equinox_3.8.1 not 3.11.1

Anyway, do you recommend me to use Kura on raspberry?

**Comment by ctron** [comment] 2017-01-12 15:50
@rita-zgheib Did you use the manual way or the Eclipse installer way?

**Comment by rita-zgheib** [comment] 2017-01-12 16:04
Both of them !

**Comment by dwoodard1** [comment] 2017-01-12 16:16
Do you need to build Kura or do you simply want to run Kura on a Raspberry Pi? If you just want to try Kura on a Raspberry Pi, I would recommend following these instructions: http://eclipse.github.io/kura/doc/raspberry-pi-quick-start.html.

We will look into the issue of building Kura on Windows.

**Comment by rita-zgheib** [comment] 2017-01-12 16:25
I want to use Kura for my platform that I am developing during my phd. The target of my project is to exchange semantic messages over MQTT in an IoT applications. For that I want to use Kura and I want to add the specifications of my application.

I have already tested Kura on the raspberry and everything is OK!

**Comment by dwoodard1** [comment] 2017-01-12 16:33
So, you likely don't need to build Kura from source. What you need is the workspace so you can begin developing your application. The correct documentation that you defined is: http://eclipse.github.io/kura/doc/kura-setup.html. The current release of Kura is v2.1.0, which uses Equinox 3.8.1. For this workflow you don't need Equinox 3.11.1 or to build Kura using the Maven commands. Just create your application in the Eclipse workspace and export your bundle. You can then install your bundle on the RPi running Kura.

You only need to run the Maven commands if you need to modify the Kura source code.

**Comment by rita-zgheib** [comment] 2017-01-12 16:35
OK, thank you so much!

**Comment by samrah1031** [comment] 2017-05-17 12:18
Hi, 

I am trying to setup eclipse kura on windows 7 using eclipse installer. But having this error :
Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-repo-equinox_3.11.1' from location file:////C:/Users/Samrah/iot-kura-develop/git/kura/kura/org.eclipse.kura.api/../target-definition/equinox_3.11.1/repository/: URI has an authority component -> [Help 1] 

Please help to resolve this issue.
Thanking you.

**Comment by cdealti** [comment] 2017-05-26 12:19
@samrah1031 unfortunately Windows is not a supported development platform. However, @markoer uses Windows and may be able to confirm your issue.

**Comment by markoer** [comment] 2017-05-26 13:42
@samrah1031: I can confirm it won't build with these settings on Windows - neither in cmd nor Cygwin. Note that 4 slashes work well in Linux while 3 may not. So you can update `manifest_pom.xml` and `features/pom.xml` and replace all `////` with `///`. You will get a bit farther, but likely not by much.

I would recommend to run the maven-related builds on Linux while you can still use IDE on Windows. Modules build just fine there with only a few exceptions.

**Comment by cdealti** [comment] 2017-06-22 21:32
To be strict we should enforce the supported operating systems and fail the build immediately.

**Comment by cdealti** [comment] 2017-07-20 12:31
@markoer #1496 has been merged. Can we close this?

**Comment by markoer** [comment] 2017-07-20 13:16
Yes.

**Closed as completed** 2017-07-21 15:20 UTC
Labels: question, kura-devenv
