### ISSUE TITLE
[Kura 2.1.0 QA] DEN-CONF-005: Internal message when a "too big" number is entered

### ISSUE THREAD

**Issue by ctron** [eclipse/kura#915] opened 2016-12-07 15:19 UTC
Entering 4294967297 shows a correct error message.

Entering 429496729733333333333 as a number shows the message: `For input string: "-429496729733333333333"`

**Comment by ctron** [comment] 2016-12-07 15:32
Also fails DEN-CONF-016

**Comment by cdealti** [comment] 2016-12-09 13:12
nice catch

**Comment by markoer** [comment] 2016-12-12 12:27
Partly a duplicate of #889.

**Comment by markoer** [comment] 2016-12-27 14:45
This happens when the value is outside of java's allowed interval for the type. And when `org.eclipse.kura.web.client.ui.AbstractServicesUi`'s `validateTextBox` parses the number, NumberFormatException is thrown and the message in question is exactly its message.

Possible options for a fix:
* use BigInteger and its shortValueExact, intValueExact, longValueExact, byteValueExact
* validate and evaluate string manually

**Closed** 2017-03-16 08:51 UTC
Labels: bug, QA
