### ISSUE TITLE
Kura 2 Webui on BeagleboneBlack Problem

### ISSUE THREAD

**Issue by giuseppeferro** [eclipse/kura#548] opened 2016-09-15 10:46 UTC
@dwoodard1 
Hi,
I have this issue on kura webui-2:

ErrorLogger INFO: : INTERNAL_ERRORorg.eclipse.kura.web.shared.GwtKuraException: INTERNAL_ERROR
at Unknown.gd(http://192.168.0.15/kura)
at Unknown.pd(http://192.168.0.15/kura)
at Unknown.CUb(http://192.168.0.15/kura)
at Unknown.HUb(http://192.168.0.15/kura)
at Unknown.g2(http://192.168.0.15/kura)
at Unknown.c2(http://192.168.0.15/kura)
at Unknown.B0(http://192.168.0.15/kura)
at Unknown.i1(http://192.168.0.15/kura)
at Unknown.eo(http://192.168.0.15/kura)
at Unknown.so(http://192.168.0.15/kura)
at Unknown.onreadystatechange<(http://192.168.0.15/kura)
at Unknown.je(http://192.168.0.15/kura)
at Unknown.me(http://192.168.0.15/kura)
at Unknown.le/<(http://192.168.0.15/kura)
at Unknown.anonymous(Unknown)

I've tried the following kura version:
kura 2.0.0 (net and no-net)  branch release
kura 2.0.1(net and no-net) branch release and develop
kura 2.1.0 (commit 8e3f791 13-09-2016 16:54) branch develop

on BeagleBone black
Linux beaglebone 4.4.15-bone11 # 1 Sun Jul 17 13:24:37 UTC 2016 armv7l GNU / Linux.
and
Linux beaglebone 4.6.7-bone-rt-r4 #1 PREEMPT RT Thu Aug 18 22:44:32 UTC 2016 armv7l GNU/Linux

osgi> ls
All Components:
ID      State                   Component Name                  Located in bundle
1       Active          org.eclipse.equinox.event                       org.eclipse.equinox.event(bid=8)
2       Active          org.eclipse.kura.data.DataService                       org.eclipse.kura.core(bid=47)
3       Active          org.eclipse.kura.db.DbService                   org.eclipse.kura.core(bid=47)
4       Active          org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport                     org.eclipse.kura.core(bid=47)
5       Active          org.eclipse.kura.ssl.SslManagerService                  org.eclipse.kura.core(bid=47)
6       Active          org.eclipse.kura.system.SystemService                   org.eclipse.kura.core(bid=47)
7       Active          org.eclipse.kura.system.SystemAdminService                      org.eclipse.kura.core(bid=47)
8       Active          org.eclipse.kura.certificate.CertificatesService                        org.eclipse.kura.core.certificates(bid=48)
9       Active          org.eclipse.kura.cloud.CloudService                     org.eclipse.kura.core.cloud(bid=49)
10      Active          org.eclipse.kura.cloud.CloudCallService                 org.eclipse.kura.core.cloud(bid=49)
11      Active          org.eclipse.kura.core.cloud.factory.DefaultCloudServiceFactory                  org.eclipse.kura.core.cloud(bid=49)
12      Active          org.eclipse.kura.cloud.app.command.CommandCloudApp                      org.eclipse.kura.core.cloud(bid=49)
13      Active          org.eclipse.kura.core.comm.CommConnectionFactory                        org.eclipse.kura.core.comm(bid=50)
14      Active          org.eclipse.kura.core.configuration.CloudConfigurationHandler                   org.eclipse.kura.core.configuration(bid=51)
15      Active          org.eclipse.kura.configuration.ConfigurationService                     org.eclipse.kura.core.configuration(bid=51)
16      Active          org.eclipse.kura.crypto.CryptoService                   org.eclipse.kura.core.crypto(bid=52)
17      Active          org.eclipse.kura.core.deployment.CloudDeploymentHandlerV2                       org.eclipse.kura.core.deployment(bid=53)
18      Active          org.eclipse.kura.log.LoggerService                      org.eclipse.kura.core.log(bid=54)
19      Active          org.eclipse.kura.status.CloudConnectionStatusService                    org.eclipse.kura.core.status(bid=56)
20      Active          org.eclipse.kura.deployment.agent                       org.eclipse.kura.deployment.agent(bid=57)
21      Active          org.eclipse.kura.clock.ClockService                     org.eclipse.kura.linux.clock(bid=58)
22      Active          org.eclipse.kura.command.CommandService                 org.eclipse.kura.linux.command(bid=59)
23      Unsatisfied             org.eclipse.kura.position.PositionService                       org.eclipse.kura.linux.position(bid=60)
24      Unsatisfied             org.eclipse.kura.usb.UsbService                 org.eclipse.kura.linux.usb(bid=61)
25      Active          org.eclipse.kura.bluetooth.BluetoothService                     org.eclipse.kura.linux.bluetooth(bid=62)
26      Active          org.eclipse.kura.watchdog.WatchdogService                       org.eclipse.kura.linux.watchdog(bid=63)
27      Active          org.eclipse.kura.camel.KuraCloudComponentResolver                       org.eclipse.kura.camel(bid=69)
28      Unsatisfied             org.eclipse.kura.camel.cloud.factory.CamelFactory                       org.eclipse.kura.camel.cloud.factory(bid=70)
29      Active          org.eclipse.kura.camel.cloud.factory.CamelManager                       org.eclipse.kura.camel.cloud.factory(bid=70)
30      Active          org.eclipse.kura.camel.xml.XmlRouterComponent                   org.eclipse.kura.camel.xml(bid=71)
31      Active          org.eclipse.kura.web.Console                    org.eclipse.kura.web(bid=73)
32      Active          org.eclipse.kura.gpio.GPIOService                       org.eclipse.kura.linux.gpio(bid=74)
33      Active          org.eclipse.kura.emulator.Emulator                      org.eclipse.kura.emulator(bid=75)
34      Active          org.eclipse.kura.net.NetworkService                     org.eclipse.kura.emulator.net(bid=76)

osgi> ss
"Framework is launched."
id State Bundle
0 ACTIVE org.eclipse.osgi_3.8.1.v20120830-144521
Fragments=2
1 ACTIVE org.eclipse.equinox.cm_1.0.400.v20120522-1841
2 RESOLVED org.eclipse.kura.sun.misc_1.0.0
Master=0
3 ACTIVE org.eclipse.equinox.common_3.6.100.v20120522-1841
4 ACTIVE org.eclipse.equinox.registry_3.5.200.v20120522-1841
5 ACTIVE org.eclipse.equinox.http.registry_1.1.200.v20120522-2049
6 ACTIVE org.eclipse.equinox.console_1.0.0.v20120522-1841
7 ACTIVE org.eclipse.equinox.ds_1.4.0.v20120522-1841
8 ACTIVE org.eclipse.equinox.event_1.2.200.v20120522-2049
9 ACTIVE org.eclipse.equinox.io_1.0.400.v20120522-2049
10 ACTIVE org.eclipse.equinox.metatype_1.2.0.v20120522-1841
11 ACTIVE org.eclipse.equinox.util_1.0.400.v20120522-2049
12 ACTIVE org.eclipse.osgi.services_3.3.100.v20120522-1822
13 ACTIVE org.eclipse.osgi.util_3.2.300.v20120522-1822
14 ACTIVE org.apache.felix.gogo.command_0.8.0.v201108120515
15 ACTIVE org.apache.felix.gogo.runtime_0.8.0.v201108120515
16 ACTIVE org.apache.felix.gogo.shell_0.8.0.v201110170705
17 ACTIVE org.knowhowlab.osgi.monitoradmin_1.0.2
18 ACTIVE org.apache.felix.dependencymanager_3.0.0
19 ACTIVE org.apache.felix.deploymentadmin_0.9.5
20 ACTIVE osgi.cmpn_4.3.0.201111022214
21 ACTIVE org.eclipse.equinox.http.jetty_3.0.0.v20120522-1841
22 ACTIVE org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841
23 ACTIVE org.eclipse.jetty.continuation_8.1.3.v20120522
24 ACTIVE org.eclipse.jetty.http_8.1.3.v20120522
25 ACTIVE org.eclipse.jetty.io_8.1.3.v20120522
26 ACTIVE org.eclipse.jetty.security_8.1.3.v20120522
27 ACTIVE org.eclipse.jetty.server_8.1.3.v20120522
28 ACTIVE org.eclipse.jetty.servlet_8.1.3.v20120522
29 ACTIVE org.eclipse.jetty.util_8.1.3.v20120522
30 ACTIVE javax.servlet_3.0.0.v201112011016
31 ACTIVE org.apache.commons.fileupload_1.2.2.v20111214-1400
32 ACTIVE org.apache.commons.io_2.4.0
33 ACTIVE slf4j.api_1.6.4
Fragments=34
34 RESOLVED slf4j.log4j12_1.6.0
Master=33
35 RESOLVED log4j_1.2.17
Fragments=36
36 RESOLVED log4j.apache-log4j-extras_1.1.0
Master=35
37 ACTIVE org.json_1.0.0.v201011060100
38 ACTIVE org.hsqldb.hsqldb_2.3.0
39 ACTIVE com.codeminders.hidapi_1.1.1
40 ACTIVE org.eclipse.soda.dk.comm_1.2.2
41 ACTIVE org.apache.commons.lang3_3.4.0
42 ACTIVE org.usb4java_1.0.0
43 ACTIVE usb4java-javax_1.0.0
44 RESOLVED jdk.dio_1.0.5
45 ACTIVE org.apache.commons.net_3.1.0.v201205071737
46 ACTIVE org.eclipse.kura.api_1.0.8
47 ACTIVE org.eclipse.kura.core_1.0.9
48 ACTIVE org.eclipse.kura.core.certificates_1.0.2
49 ACTIVE org.eclipse.kura.core.cloud_1.0.8
50 ACTIVE org.eclipse.kura.core.comm_1.0.2
51 ACTIVE org.eclipse.kura.core.configuration_1.0.8
52 ACTIVE org.eclipse.kura.core.crypto_1.0.4
53 ACTIVE org.eclipse.kura.core.deployment_1.1.1
54 ACTIVE org.eclipse.kura.core.log_1.0.1
55 ACTIVE org.eclipse.kura.core.net_1.0.8
56 ACTIVE org.eclipse.kura.core.status_1.0.1
57 ACTIVE org.eclipse.kura.deployment.agent_1.0.6
58 ACTIVE org.eclipse.kura.linux.clock_1.0.6
59 ACTIVE org.eclipse.kura.linux.command_1.0.4
60 STARTING org.eclipse.kura.linux.position_1.0.6
61 ACTIVE org.eclipse.kura.linux.usb_1.0.7
62 ACTIVE org.eclipse.kura.linux.bluetooth_1.0.5
63 ACTIVE org.eclipse.kura.linux.watchdog_1.0.5
64 RESOLVED org.eclipse.kura.camel.sun.misc_1.0.0
Master=65
65 RESOLVED org.apache.camel.camel-core_2.16.0
Fragments=64
66 RESOLVED org.apache.camel.camel-core-osgi_2.16.0
67 RESOLVED org.apache.camel.camel-kura_2.16.0
68 ACTIVE org.eclipse.kura.camel_1.0.1
69 RESOLVED com.gwt.user_1.0.0
70 ACTIVE org.eclipse.kura.web_2.0.1
71 ACTIVE org.eclipse.kura.linux.gpio_1.0.1
72 ACTIVE org.eclipse.kura.emulator_1.0.7
73 ACTIVE org.eclipse.kura.emulator.net_1.0.1
74 ACTIVE org.tigris.mtoolkit.iagent.rpc_3.0.0.20110411-0918

root@beaglebone:~# ps aux | grep java
root 676 24.0 26.5 360100 134364 ? Sl 08:07 0:32 java -Xms256m -Xmx256m -XX:MaxPermSize=64m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/kura-heapdump.hprof -XX:ErrorFile=/var/log/kura-error.log -Dkura.os.version=debian -Dkura.arch=armv7_hf -Dtarget.device=beaglebone -Declipse.ignoreApp=true -Dkura.home=/opt/eclipse/kura/kura -Dkura.configuration=file:/opt/eclipse/kura/kura/kura.properties -Dkura.custom.configuration=file:/opt/eclipse/kura/kura/kura_custom.properties -Dkura.data.dir=/opt/eclipse/kura/data -Ddpa.configuration=/opt/eclipse/kura/kura/dpa.properties -Dlog4j.configuration=file:/opt/eclipse/kura/kura/log4j.properties -Djava.security.policy=/opt/eclipse/kura/kura/jdk.dio.policy -Djdk.dio.registry=/opt/eclipse/kura/kura/jdk.dio.properties -Djdk.tls.trustNameService=true -jar /opt/eclipse/kura/plugins/org.eclipse.osgi_3.8.1.v20120830-144521.jar -configuration /tmp/.kura/configuration -console 5002 -consoleLog

root@beaglebone:~# netstat -tulnp | grep 80
tcp6 0 0 :::80 :::* LISTEN 676/java
tcp6 0 0 :::8080 :::* LISTEN 839/apache2

I've tried Edge,Chrome and Firefox...all the same story!

Thanks for your help

**Comment by dwoodard1** [comment] 2016-09-15 18:06
@giuseppeferro I believe I have reproduced the error. Could you please post the output of the /var/log/kura-console.log file?

**Comment by dwoodard1** [comment] 2016-09-15 19:03
@giuseppeferro Based on your 'ls' output, I am pretty sure you are having the same problem. These steps resolved the issue for me:

1. Stop Kura
2. Execute: ln -s /lib/arm-linux-gnueabihf/libudev.so.1 /lib/arm-linux-gnueabihf/libudev.so.0
3. Start Kura

We are investigating a long term solution.

**Comment by giuseppeferro** [comment] 2016-09-16 07:37
@dwoodard1 Issue resolved.
Thanks.
I hope you will find a long term solution.

**Comment by ctron** [comment] 2016-09-16 09:28
Seems like a duplicate of #321

**Comment by dwoodard1** [comment] 2016-09-16 13:32
Closing this issue. We will track the long term fix with #321 .

**Closed by dwoodard1** 2016-09-16 13:32 UTC
