### ISSUE TITLE
[Kura 2.1.0 QA] eth0 search domain configuration and storage

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#923] opened 2016-12-09 15:03 UTC
Outside of test NET-ETH0-006 (#788) scope, but still related: if filled, search domain is neither added to /etc/resolv.conf nor stored in Kura configuration.

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by cdealti** [comment] 2016-12-09 16:36
@ibinshtok can you please just check if this is a regression. I've never tried to set search domains, even with the old Web UI.

**Comment by ibinshtok** [comment] 2016-12-09 23:54
@cdealti I don't think it is a regression issue since it has never been fully implemented.
As of right now, we are adding search domains (WIN Servers) to the list of DNS servers (the netConfig4.setDnsServers() call  in the updateNetInterfaceConfigurations() method of the GwtNetworkServiceImpl class) which is not correct, I believe. And after that we overwrite this list by actually supplying DNS servers. For the search domains we should probably use the netConfig4.setDomains() call instead which should result in the /etc/resolv.conf to be set with the 'search' line as shown below. 
 
search example.com company.net
nameserver 8.8.8.8

But this is not supported in the org.eclipse.kura.linux.net.dns.LinuxDns
Please let me know if you want me to fix this for the Kura 2.1.0 release.

**Comment by cdealti** [comment] 2016-12-12 09:22
Thanks. Postponed

**Comment by markoer** [comment] 2017-04-14 13:23
The annoying part of this for the user is the warning in the log:
```
WARN  o.e.k.w.s.GwtNetworkServiceImpl - Failed
java.net.UnknownHostException: <domain>: unknown error
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.eclipse.kura.net.IPAddress.parseHostAddress(IPAddress.java:94)
        at org.eclipse.kura.web.server.GwtNetworkServiceImpl.updateNetInterfaceConfigurations(GwtNetworkServiceImpl.java:791)
```

**Comment by cdealti** [comment] 2018-04-27 10:12
Closing favoring #1993.

**Closed by cdealti** 2018-04-27 10:12 UTC
Labels: bug, kura-net
