### ISSUE TITLE
[Web UI] Settings pages

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#864] opened 2016-11-30 12:57 UTC
System->Settings page has no password change capability. It is hidden under Services->WebConsole.

Now for the actual issue...
If I want to modify the password, I update the password field. If I click apply while still in the updated password field, it is not applied. The click only enables the buttons. The second click works. I doubt that's by design, but happens all over the GUI. This provides for a rather bad user experience.

Also, Apply button could be the default form action button i.e. I could update the field(s), press Enter and be done.

Kura 2.1.0 build 12 on Raspberry Pi 3
Various browsers, including Chrome, Firefox and IE.

**Comment by cdealti** [comment] 2016-12-01 08:42
@markoer it's by design. We'll take a look after 2.1.0 is out

**Comment by djurod** [comment] 2016-12-12 14:25
Also an issue on BeagleBone Black (#791).

**Comment by cdealti** [comment] 2017-02-28 14:14
@MMaiero I believe this is "normal" but also annoying. Is there something we can do?
If not I believe we can close this

**Comment by djurod** [comment] 2017-02-28 14:21
I suspect that the button's enable state is updated only when the password field looses focus. If you changed this to update the button's enable state immediately when the field is changed, you could probably solve this.

Since this is something that is done practically all over the place in the Web UI, this would probably be a quite big task and potentially error prone.

It would probably make sense to keep this in mind when/if the Web UI is redesigned, but fixing it in the current implementation might not be worth it...

**Closed** 2017-07-04 15:58 UTC
Labels: enhancement, kura-web2
