### ISSUE TITLE
[Kura 2.1.0 QA] Raspberry Pi 3 uninstall leaves files

### ISSUE THREAD

**Issue by markoer** [eclipse/kura#921] opened 2016-12-09 10:34 UTC
Uninstallation script (`distrib/src/main/deb/control/prerm`) doesn't remove the actual installation directory, only the link to it. What it does remove is probably the only directory I might want to keep - `data/`.
A comment in the file also states that removal of Eclipse directory will be attempted, but it's not. It might be a good idea to remove it, but only if it's empty i.e. no other Eclipse software there.

```
# apt-get purge kura
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  kura*
0 upgraded, 0 newly installed, 1 to remove and 13 not upgraded.
After this operation, 49.6 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 121583 files and directories currently installed.)
Removing kura (2.1.0) ...

Uninstalling KURA...
#
```
This remains afterward:
```
# ls -la /opt/eclipse/
total 12
drwxr-xr-x 3 root root 4096 Dec  9 10:17 .
drwxr-xr-x 7 root root 4096 Nov 28 12:34 ..
drwxr-xr-x 7 root root 4096 Dec  9 10:17 kura_2.1.0_raspberry-pi-2
# find /opt/eclipse/kura_2.1.0_raspberry-pi-2/
/opt/eclipse/kura_2.1.0_raspberry-pi-2/
/opt/eclipse/kura_2.1.0_raspberry-pi-2/plugins
/opt/eclipse/kura_2.1.0_raspberry-pi-2/plugins/org.eclipse.osgi.services_3.3.100.v20120522-1822.jar
/opt/eclipse/kura_2.1.0_raspberry-pi-2/plugins/org.eclipse.equinox.app_1.3.100.v20120522-1841.jar
... many more
```

Kura 2.1.0 build 12, Raspberry Pi 3

**Comment by ctron** [comment] 2016-12-09 10:41
Looks like a duplicate of #362

**Comment by markoer** [comment] 2016-12-09 12:31
Correct. I somehow didn't find it before.

**Comment by cdealti** [comment] 2016-12-09 13:04
Duplicate of #362

**Closed** 2016-12-09 13:04 UTC
Labels: duplicate
